# -*- mode: python -*-
import platform
Import('env')
env = env.Clone();

slice_array_ut_libs = [
    'indexlib_basic',
    'fslib-framework',
    'autil',
    'gmock',
    'gtest',
    'pthread'
]

slice_array_case_cpps=Glob('*_unittest.cpp')
slice_array_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    slice_array_case_cpps,
]

env.aTest(target = 'ie_slice_array_unittest',
          source = slice_array_ut_test_sources,
          LIBS= slice_array_ut_libs)

