# -*- mode: python -*-
Import('env')
env = env.Clone()

unittestcpps = [
    '#indexlib/test/dotest.cpp',
    'number_index_reader_unittest.cpp',
]

env.aTest('indexlib_number_unittest', unittestcpps,  LIBS=[
    'indexlib_packtest',
    'indexlib_attributetest',
    'indexlib_indextest_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'fslib-framework',
    'gtest',
    'gmock',
    'pthread'
]
)

Return([])

