package(default_visibility=['//aios/ha3:__subpackages__'])
cc_library(
    name='modelconfig',
    hdrs=glob(['ModelConfig.h']),
    include_prefix='ha3/turing/common',
    visibility=['//visibility:public'],
    deps=['//aios/autil:json', '//aios/ha3:ha3_isearch_h']
)
