package(default_visibility=['//aios/ha3:__subpackages__'])
cc_library(
    name='sql_graph_optimize_base',
    hdrs=glob(['GraphOptimizer.h']),
    deps=['//aios/sql/iquan/cpp/common:iquan_common'],
    include_prefix='ha3/sql/ops/planOptimize',
    alwayslink=True
)
