# -*- mode: python -*-

Import('env')
env = env.Clone()

trie_test_sources = [
    '#indexlib/test/dotest.cpp',
    'trie_index_intetest.cpp',
    'trie_index_merger_unittest.cpp',
    'double_array_trie_unittest.cpp',
]

trie_libs = [
    'indexlib_indextest_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
    'pthread'
]

env.aTest(target = 'ie_trie_unittest', 
          source = trie_test_sources, LIBS = trie_libs)


