# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

test_sources = Glob('*.cpp')

env.aTest(target = 'ops_condition_test',
          source = test_sources,
          LIBS = ['ha3sdk_testlib','ha3_fakesearch'] + env['ha3_test_depend_lib']);
