load('//aios/storage:defs.bzl', 'strict_cc_fast_test')
strict_cc_fast_test(
    name='SourceGroupConfigTest',
    srcs=['SourceGroupConfigTest.cpp'],
    copts=['-fno-access-control'],
    deps=[
        '//aios/storage/indexlib/index/source/config:SourceGroupConfig',
        '//aios/unittest_framework'
    ]
)
