# -*- mode: python -*-

Import('env')
env = env.Clone()

sources = Glob('*.cpp')

env.aStaticLibraryAndInstall(
    target = 'knn_params_selector',
    source = sources
)

env.aDirs('test')
Return('sources')