# -*- mode: python -*-

Import('env')
env = env.Clone()

util_cache_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    'search_cache_creator_unittest.cpp',
]

env.aTest(target = 'indexlib_util_cache_unittest',
          source = util_cache_ut_test_sources,
          LIBS= ['indexlib_basic', 'autil', 'gmock', 'gtest'])
