load('//aios/storage:defs.bzl', 'strict_cc_fast_test')
strict_cc_fast_test(
    name='SourceIndexFileTest',
    srcs=['SourceIndexFileTest.cpp'],
    deps=[
        '//aios/storage/indexlib/file_system',
        '//aios/storage/indexlib/index/source:constants',
        '//aios/unittest_framework'
    ]
)
