package(default_visibility=['//aios/table:__subpackages__'])
cc_library(
    name='table_testlib',
    hdrs=['MatchDocUtil.h', 'TableTestUtil.h'],
    include_prefix='table/test',
    visibility=['//visibility:public'],
    deps=['//aios/table']
)
