# -*- mode: python -*-

Import('env')
env = env.Clone()

document_rawdoc_ut_libs = [
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
]

document_rawdoc_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    'default_raw_document_unittest.cpp',
    'key_map_unittest.cpp',
    'key_map_manager_unittest.cpp',
]

env.aTest(target = 'indexlib_document_rawdoc_unittest',
          source = document_rawdoc_ut_test_sources,
          LIBS = document_rawdoc_ut_libs)
