cc_test(
    name='matchdoc_test',
    srcs=glob(['*.cpp', '*.h']),
    copts=['-fno-access-control'],
    deps=[
        '//aios/matchdoc', '//aios/matchdoc:matchdoc_toolkit',
        '@com_google_googletest//:gtest'
    ]
)
