# -*- mode: python -*-

Import('env')
env = env.Clone()

spatial_test_sources = [
    '#indexlib/test/dotest.cpp',
    'spatial_index_intetest.cpp',
    'spatial_index_reader_unittest.cpp',
    'spatial_posting_iterator_unittest.cpp',
]

spatial_libs = [
    'indexlib_indextest_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
    'pthread'
]

env.aTest(target = 'ie_spatial_unittest', 
          source = spatial_test_sources, LIBS = spatial_libs)


