package(default_visibility=['//aios/apps/facility/cm2:__subpackages__'])
cc_library(
    name='config',
    srcs=['subscriber_config.cpp'],
    hdrs=['subscriber_config.h'],
    deps=['//aios/apps/facility/cm2/cm_basic/basic_struct:basic_struct'],
    implementation_deps=['//third_party/mxml:mxml']
)
