load('//aios/storage/indexlib:defs.bzl', 'indexlib_cc_library')
indexlib_cc_library(
    name='all',
    srcs=[],
    hdrs=[],
    visibility=['//visibility:public'],
    deps=([
        '//aios/storage/indexlib/table/aggregation:table',
        '//aios/storage/indexlib/table/kkv_table:table',
        '//aios/storage/indexlib/table/kv_table:table',
        '//aios/storage/indexlib/table/normal_table:table'
    ] + [])
)
indexlib_cc_library(
    name='builtin_define',
    srcs=[],
    hdrs=['BuiltinDefine.h'],
    visibility=['//visibility:public']
)
