# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

queryparser_perftest_sources = ['ScannerUnitPerfTest.cpp',
                                'BisonParserPerfTest.cpp',
                                '#ha3/test/dotest.cpp',]

libsname = ['ha3_queryparser',
            'ha3_common', 'ha3_util', 'ha3_rank', 'ha3_config', 'ha3_sorter',
            'ha3_proxy', 'ha3_search', 'ha3_fakequeryparser',
            'mxml',
            ]

#env.Append(LIBS = libsname)

tempsource = queryparser_perftest_sources

env.aTest(target = 'queryparser_perftest', 
          source = tempsource,
          LIBS = [libsname, 'indexlib', 'AliWS', 'dl']
          )






