# -*- mode: python -*-

Import('env')
env = env.Clone()
source = Glob('*.cpp')

depend_libs = ['ha3_sql_data']

env.aLibrary(target = 'ha3_sql_rank',
                   source = source,
                   LIBS = depend_libs)

env.aDirs('test')

Return('source')
