package(default_visibility=['//aios/ha3:__subpackages__'])
cc_library(
    name='sql_ops_values',
    srcs=glob(['*.cpp']),
    hdrs=glob(['*.h']),
    deps=['//aios/ha3/ha3/sql/ops/util:sql_ops_util', '//navi:navi'],
    include_prefix='ha3/sql/ops/values',
    alwayslink=True
)
