# -*- mode: python -*-
import platform
Import('env')
env = env.Clone();

field_format_pack_attr_ut_libs = [
    'indexlib_testlib',
    'indexlib_configtest',
    'indexlib_indextest_common',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_common',
    'indexlib_document',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'fslib-framework',
    'autil',
    'gmock',
    'gtest',
    'pthread'
]

field_format_pack_attr_case_cpps=Glob('*_unittest.cpp')
field_format_pack_attr_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    field_format_pack_attr_case_cpps,
]

# lib_attrs = {}
# for lib in field_format_pack_attr_ut_libs:
#     lib_attrs[lib] = "shared"

env.aTest(target = 'ie_field_format_pack_attr_unittest',
          source = field_format_pack_attr_ut_test_sources,
          LIBS= field_format_pack_attr_ut_libs)
#          LIBATTRS = lib_attrs)

