load('//aios/storage/indexlib:defs.bzl', 'indexlib_cc_library')
package(default_visibility=['//aios/storage/indexlib:__subpackages__'])
indexlib_cc_library(
    name='OfflineMergeConfig',
    deps=['//aios/storage/indexlib/config:MergeConfig', '//aios/autil:json']
)
