load('//aios/storage:defs.bzl', 'strict_cc_library')
package(default_visibility=['//aios/storage/indexlib:__subpackages__'])
strict_cc_library(
    name='OfflineMergeConfig',
    deps=['//aios/autil:json', '//aios/storage/indexlib/config:MergeConfig']
)
