# -*- mode: python -*-

Import('env')
env = env.Clone()

attribute_accessor_cpps=Glob('*.cpp')
#env.aLibrary(target='indexlib_attribute_accessor', source=attribute_accessor_cpps)

# env.aDirs('test')
# env.aDirs('perf_test')
Return(['attribute_accessor_cpps'] )


