# -*- mode: python -*-

Import('env')
env = env.Clone()

inverted_index_perf_test_sources_for_gtest = [
    '#indexlib/test/dotest.cpp',
    'suspendable_thread.cpp',
    'doc_list_encoder_perf_unittest.cpp',
    'position_list_encoder_perf_unittest.cpp',
    'buffered_byte_slice_perf_unittest.cpp',
    'in_mem_doc_list_decoder_perf_unittest.cpp',
    'in_mem_position_list_decoder_perf_unittest.cpp',
    'in_mem_bitmap_posting_iterator_perf_unittest.cpp',
    'bitmap_index_perf_intetest.cpp',
]

inverted_perf_libs = [
    'indexlib_indextest_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
]

env.aTest(target = 'indexlib_inverted_index_perftest_for_gtest', 
          source = inverted_index_perf_test_sources_for_gtest,
          LIBS = inverted_perf_libs)


