
workspace(name='com_taobao_aios')
load('//:workspace.bzl', 'aios_workspace')
aios_workspace()
load('@com_github_mjbots_bazel_deps//tools/workspace:default.bzl', 'add_default_repositories')
add_default_repositories()
load('@rules_foreign_cc//:workspace_definitions.bzl', 'rules_foreign_cc_dependencies')
rules_foreign_cc_dependencies()
load('@org_tensorflow//tensorflow:version_check.bzl', 'check_bazel_version_at_least')
check_bazel_version_at_least('0.24.1')
load('@org_tensorflow//tensorflow:workspace.bzl', 'tf_workspace')
tf_workspace(path_prefix='', tf_repo_name='org_tensorflow')
load('@tvm//:workspace.bzl', 'tvm_workspace')
tvm_workspace()
load('@rules_pkg//:deps.bzl', 'rules_pkg_dependencies')
rules_pkg_dependencies()
load('@bazel_skylib//:workspace.bzl', 'bazel_skylib_workspace')
bazel_skylib_workspace()
