# -*- mode: python -*-

Import('env')
env = env.Clone()

open_executor_test_sources = [
    '#indexlib/test/dotest.cpp',
    'open_executor_chain_unittest.cpp',
    'dump_container_flush_executor_unittest.cpp',
]

open_executor_libs = [
    'indexlib_test',
    'indexlib_indextest_common',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
]

env.aTest(target = 'ie_open_executor_unittest', 
          source = open_executor_test_sources, LIBS = open_executor_libs)
