# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

testlib_sorter_sources = Glob('*.cpp')

testlib_sorter = env.aStaticLibrary(target = 'testlib_sorter', source = testlib_sorter_sources)

#env.aDirs('test')

Return(['testlib_sorter_sources'])
