load('//aios/storage/indexlib:defs.bzl', 'indexlib_cc_library')
package(default_visibility=['//aios/storage/indexlib:__subpackages__'])
indexlib_cc_library(
    name='SourceGroupConfig',
    deps=[
        '//aios/autil:json', '//aios/autil:log',
        '//aios/storage/indexlib/base:Status',
        '//aios/storage/indexlib/base:Types',
        '//aios/storage/indexlib/base:constants',
        '//aios/storage/indexlib/config:ConfigDefine',
        '//aios/storage/indexlib/config:GroupDataParameter',
        '//aios/storage/indexlib/index/source:constants',
        '//aios/storage/indexlib/util:Exception'
    ]
)
