package(default_visibility=['//aios/autil:__subpackages__'])
cc_library(
    name='json_testlib',
    hdrs=['JsonTestUtil.h'],
    srcs=['JsonTestUtil.cpp'],
    deps=['//aios/autil:json_helper', '//aios/unittest_framework:unittest_lib'],
    include_prefix='autil/legacy/test',
    visibility=['//visibility:public'],
    testonly=True
)
