package(default_visibility=['//aios/autil:__subpackages__'])
cc_library(
    name='json_testlib',
    testonly=True,
    srcs=['JsonTestUtil.cpp'],
    hdrs=['JsonTestUtil.h'],
    include_prefix='autil/legacy/test',
    visibility=['//visibility:public'],
    deps=['//aios/autil:json_helper', '//aios/unittest_framework:unittest_lib']
)
