# -*- mode: python -*-

Import('env')
env = env.Clone()

accessor = env.aDirs('accessor')
format = env.aDirs('format')

attribute=Glob('*.cpp')
attributecpps = [accessor, format, attribute]

#env.aLibrary(target='indexlib_attribute', source=attributecpps)

env.aDirs('test')
env.aDirs('perf_test')

Return(['attributecpps'] )
