ARPC_TIME_OUT = 6  # seconds

SWIFT_TOOLS_CONFIG_SECTION_NAME = "swift_tools"
SWIFT_TOOLS_CONFIG_FS_UTIL_EXE = "fs_util_exe"
SWIFT_TOOLS_CONFIG_INSTALL_PERFIX = "install_prefix"
SWIFT_TOOLS_CONFIG_LIB_PATH = "lib_path"
SWIFT_TOOLS_CONFIG_HADOOP_HOME = "hadoop_home"
SWIFT_TOOLS_CONFIG_CLASS_PATH_UTIL = "class_path_util"

SWIFT_METHOD_CREATE_TOPIC = "createTopic"
SWIFT_METHOD_CREATE_TOPIC_BATCH = "createTopicBatch"
SWIFT_METHOD_MODIFY_TOPIC = "modifyTopic"
SWIFT_METHOD_DELETE_TOPIC = "deleteTopic"
SWIFT_METHOD_DELETE_TOPIC_BATCH = "deleteTopicBatch"
SWIFT_GET_ALL_MACHINE_ADDRESS = "getAllMachineAddress"
SWIFT_METHOD_GET_ALL_TOPIC_NAME = "getAllTopicName"
SWIFT_METHOD_GET_TOPIC_INFO = "getTopicInfo"
SWIFT_METHOD_GET_ALL_TOPIC_INFO = "getAllTopicInfo"
SWIFT_METHOD_GET_ALL_TOPIC_SIMPLE_INFO = "getAllTopicSimpleInfo"
SWIFT_METHOD_TOPIC_ACL_MANAGE = "topicAclManage"
SWIFT_METHOD_GET_ROLE_ADDRESS = "getRoleAddress"
SWIFT_METHOD_GET_ALL_WORKER_STATUS = "getAllWorkerStatus"
SWIFT_METHOD_GET_WORKER_ERROR = "getWorkerError"
SWIFT_METHOD_GET_PARTITION_ERROR = "getPartitionError"
SWIFT_METHOD_UPDATE_CONFIG = "updateConfig"
SWIFT_METHOD_UPDATE_BROKER_CONFIG = "updateBrokerConfig"
SWIFT_METHOD_ROLLBACK_BROKER_CONFIG = "rollbackBrokerConfig"

SWIFT_METHOD_SEND_MESSAGE = "sendMessage"
SWIFT_METHOD_GET_MESSAGE = "getMessage"
SWIFT_METHOD_GET_MAX_MESSAGE_ID = "getMaxMessageId"
SWIFT_METHOD_GET_MIN_MESSAGE_ID_BY_TIME = "getMinMessageIdByTime"

SWIFT_METHOD_TRANSFER_PARTITION = "transferPartition"
SWIFT_METHOD_CHANGE_SLOT = "changeSlot"
SWIFT_METHOD_REGISTER_SCHEMA = "registerSchema"
SWIFT_METHOD_GET_SCHEMA = "getSchema"
SWIFT_METHOD_GET_BROKER_STATUS = "getBrokerStatus"
SWIFT_METHOD_GET_TOPIC_RWTIME = "getTopicRWTime"
SWIFT_METHOD_GET_LAST_DELETED_NOUSE_TOPIC = "getLastDeletedNoUseTopic"
SWIFT_METHOD_GET_DELETED_NOUSE_TOPIC = "getDeletedNoUseTopic"
SWIFT_METHOD_GET_DELETED_NOUSE_TOPIC_FILES = "getDeletedNoUseTopicFiles"
SWIFT_METHOD_UPDATE_WRITER_VERSION = "updateWriterVersion"
SWIFT_METHOD_TURN_TO_MASTER = "turnToMaster"

SWIFT_CONF_FILE_NAME = 'swift.conf'
SWIFT_CONF_COMMON_SECTION_NAME = "common"
SWIFT_CONF_ADMIN_SECTION_NAME = "admin"
SWIFT_CONF_BROKER_SECTION_NAME = "broker"
SWIFT_CONF_LOG_CONF = "log_conf"
SWIFT_CONF_HADOOP_HOME = "hadoop_home"
SWIFT_CONF_LIB_PATH = "lib_path"
SWIFT_CONF_BIND_PORT = "bind_port"
SWIFT_CONF_DATA_ROOT_PATH = "data_root_path"
SWIFT_CONF_COMMON_SECTION_NECESSARY_FIELDS = [SWIFT_CONF_LOG_CONF, SWIFT_CONF_LIB_PATH,]
SWIFT_CONF_ADMIN_SECTION_NECESSARY_FIELDS = [SWIFT_CONF_BIND_PORT]
SWIFT_CONF_BROKER_SECTION_NECESSARY_FIELDS = [SWIFT_CONF_BIND_PORT]

SWFIT_ADMIN_EXE = "swift_admin"
SWFIT_BROKER_EXE = "swift_broker"

GET_ADMIN_LEADER_TRY_TIMES = 5

SWIFT_ERROR_NONE = 0

PROTO_ERROR_INFO = "errorInfo"
PROTO_ERROR_CODE = "errCode"
PROTO_ERROR_MSG = "errMsg"
PROTO_TOPIC_INFO = "topicInfo"
PROTO_NAMES = "names"
PROTO_ADDRESS_LIST = "addressList"
PROTO_ADDRESS_GROUP = "addressGroup"
PROTO_ADDRESS = "address"
PROTO_SYS_STOP = "sysStop"
PROTO_START_TIME_SEC = "startTimeSec"
PROTO_BROKER_ADDRESS = "brokerAddress"
PROTO_STATUS = "status"
PROTO_MSG_ID = "msgId"
PROTO_TIME_STAMP = "timestamp"
PROTO_ACCEPTED_MSG_COUNT = "acceptedMsgCount"
PROTO_MAX_ALLOW_MSG_LEN = "maxAllowMsgLen"
PROTO_MAX_MSG_ID = "maxMsgId"
PROTO_MAX_TIME_STAMP = "maxTimestamp"
PROTO_NEXT_MSG_ID = "nextMsgId"
PROTO_NEXT_TIME_STAMP = "nextTimestamp"
PROTO_TRACE_TIME_INFO = "traceTimeInfo"
PROTO_REQUEST_RECIVED_TIME = "requestRecivedTime"
PROTO_RESPONSE_DONE_TIME = "responseDoneTime"

PART_SORT_PART_ID = 'partid'
PART_SORT_PART_STATUS = 'partstatus'
PART_SORT_BROKER_ADDRESS = 'brokeraddress'
