# -*- mode: python -*-

Import('env')

env = env.Clone()

libsorter_sources =  [
    'SorterProvider.cpp',
    'DefaultSorter.cpp',
    'NullSorter.cpp',
    'SorterResource.cpp',
    'BuildinSorterModuleFactory.cpp',
    ]

env.aLibrary(target = 'ha3_sorter',
             source = libsorter_sources)

env.aDirs('test')
