# -*- mode: python -*-

Import('env')
env = env.Clone()

compress_perf_test_sources = [
    '#indexlib/test/dotest.cpp',
    'equivalent_compress_perf_unittest.cpp',
]

compress_libs = [
    'indexlib_basic',
    'gmock',
    'gtest',
    'pthread',
]

env.aTest(target = 'indexlib_compress_perf_test',
          source = compress_perf_test_sources,
          LIBS= compress_libs)


