# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')
import os

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

env['depend_static_libs'] =  []

env['depend_dynamic_libs'] = [
    'ha3_queryparser_util',
    'ha3_suez_turing_agg_opdef', 
    'ha3_suez_turing_search',
    'suez_turing',
    'suez',
    'build_service',
    'indexlib',
    'turing_ops',
    'basic_variant',
    'iquan_jni',
    'iquan_common',
    'navi',
    'matchdoc',
    'swift_client_minimal',
    'cava',
    'hippo',
    'multi_call',
    'fslib-framework',
    'amonitor_client',
    'kmonitor_client',
    'kmonitor_adapter',
    'resource_reader',
    'cm_basic',
    'cm_sub',
    'sap_eagle',
    'eagleeye_core',
    'mid-diamond',
    'worker_framework',
    'http_arpc',
    'kvtracer',
    'autil',
    'arpc',
    'anet',
    'sap',
    'alog',
    'z',
    'dl',
    'xml2',
    'snappy',
    'lz4',
    'zstd',
    'protobuf',
    'pthread',
    'sap_eagle',
    'hiredis',
    'zookeeper_mt',
    'tensorflow_cc',
    'absl_strings',
]

env['ha3_libs'] = [
]

env['ha3_depend_libs'] = env['depend_static_libs'] + env['depend_dynamic_libs'] + env['ha3_libs']

env['ha3_test_depend_lib'] = env['ha3_depend_libs'] + ['unittest', 'gmock', 'gtest']


# List my sub-directories.
def getSubdirs(abs_path_dir) :
    lst = [ name for name in os.listdir(abs_path_dir) if os.path.isdir(os.path.join(abs_path_dir, name)) and name[0] != '.' ]
    return lst

function_plugins = []

# function_common = env.aDirs('common')

for plugin_dir in getSubdirs(Dir('.').srcnode().abspath):
    if plugin_dir in ['docs','testlib','testdata', 'build', "runtime_testdata", "util"]:
        continue
    ret = env.aDirs(plugin_dir)
    function_plugins.append(ret)

linkflags = []
linkflags.append('-Wl,--whole-archive')
for lib in function_plugins:
    linkflags.append("%s/lib/lib%s.a" % (env['ABS_BUILD_DIR'], lib))
linkflags.append('-Wl,--no-whole-archive')
env.Append(LINKFLAGS=linkflags)

env.aSharedLibraryAndInstall(target = 'function_example',
    source = [],
    LIBS = function_plugins)