# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

testlib_search_sources = Glob('*.cpp')

#fakesearch = env.aLibrary(target = 'ha3_fakesearch', source = fake_search_sources)

#env.aDirs('test')

Return(['testlib_search_sources'])
