# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

# List my sub-directories.
env.aDirs('qrsprocessor')
env.aDirs('scorer')
env.aDirs('summary')
env.aDirs('documentProcessor')
env.aDirs('functions')
env.aDirs('PluginCommunication')
env.aDirs('final_sorter')
