// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iquan.proto

package com.taobao.search.iquan.client.common.pb;

public final class Iquan {
  private Iquan() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_AnyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_AnyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_AnyValueList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_AnyValueList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_AnyValueMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_AnyValueMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_AnyValueMap_ValueEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_AnyValueMap_ValueEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_IdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_IdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_PlanOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_PlanOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_PlanOp_InputsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_PlanOp_InputsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_PlanOp_AttrsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_PlanOp_AttrsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_SqlPlan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_SqlPlan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_SqlPlan_OptimizeInfosEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_SqlPlan_OptimizeInfosEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_SqlPlan_ExecParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_SqlPlan_ExecParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_SqlQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_SqlQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iquan_pb_SqlQueryResponse_DebugInfosEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iquan_pb_SqlQueryResponse_DebugInfosEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013iquan.proto\022\010iquan.pb\"\347\001\n\010AnyValue\022\024\n\n" +
      "bool_value\030\001 \001(\010H\000\022\023\n\tint_value\030\002 \001(\005H\000\022" +
      "\024\n\nlong_value\030\003 \001(\003H\000\022\026\n\014double_value\030\004 " +
      "\001(\001H\000\022\026\n\014string_value\030\005 \001(\tH\000\022,\n\nlist_va" +
      "lue\030\006 \001(\0132\026.iquan.pb.AnyValueListH\000\022*\n\tm" +
      "ap_value\030\007 \001(\0132\025.iquan.pb.AnyValueMapH\000B" +
      "\020\n\016AnyValue_oneof\"1\n\014AnyValueList\022!\n\005val" +
      "ue\030\001 \003(\0132\022.iquan.pb.AnyValue\"\200\001\n\013AnyValu" +
      "eMap\022/\n\005value\030\001 \003(\0132 .iquan.pb.AnyValueM" +
      "ap.ValueEntry\032@\n\nValueEntry\022\013\n\003key\030\001 \001(\t" +
      "\022!\n\005value\030\002 \001(\0132\022.iquan.pb.AnyValue:\0028\001\"" +
      "\025\n\006IdList\022\013\n\003ids\030\001 \003(\005\"\251\002\n\006PlanOp\022\n\n\002id\030" +
      "\001 \001(\005\022\017\n\007op_name\030\002 \001(\t\022,\n\006inputs\030\003 \003(\0132\034" +
      ".iquan.pb.PlanOp.InputsEntry\022\024\n\014reuse_in" +
      "puts\030\005 \003(\005\022\017\n\007outputs\030\004 \003(\005\022*\n\005attrs\030\006 \003" +
      "(\0132\033.iquan.pb.PlanOp.AttrsEntry\032?\n\013Input" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022\037\n\005value\030\002 \001(\0132\020.iqu" +
      "an.pb.IdList:\0028\001\032@\n\nAttrsEntry\022\013\n\003key\030\001 " +
      "\001(\t\022!\n\005value\030\002 \001(\0132\022.iquan.pb.AnyValue:\002" +
      "8\001\"\272\002\n\007SqlPlan\022\030\n\020rel_plan_version\030\001 \001(\t" +
      "\022\"\n\010rel_plan\030\002 \003(\0132\020.iquan.pb.PlanOp\022<\n\016" +
      "optimize_infos\030\003 \003(\0132$.iquan.pb.SqlPlan." +
      "OptimizeInfosEntry\0226\n\013exec_params\030\004 \003(\0132" +
      "!.iquan.pb.SqlPlan.ExecParamsEntry\032H\n\022Op" +
      "timizeInfosEntry\022\013\n\003key\030\001 \001(\t\022!\n\005value\030\002" +
      " \001(\0132\022.iquan.pb.AnyValue:\0028\001\0321\n\017ExecPara" +
      "msEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"" +
      "\350\001\n\020SqlQueryResponse\022\022\n\nerror_code\030\001 \001(\005" +
      "\022\025\n\rerror_message\030\002 \001(\t\022?\n\013debug_infos\030\003" +
      " \003(\0132*.iquan.pb.SqlQueryResponse.DebugIn" +
      "fosEntry\022!\n\006result\030\004 \001(\0132\021.iquan.pb.SqlP" +
      "lan\032E\n\017DebugInfosEntry\022\013\n\003key\030\001 \001(\t\022!\n\005v" +
      "alue\030\002 \001(\0132\022.iquan.pb.AnyValue:\0028\001B/\n(co" +
      "m.taobao.search.iquan.client.common.pbP\001" +
      "\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_iquan_pb_AnyValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iquan_pb_AnyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_AnyValue_descriptor,
        new java.lang.String[] { "BoolValue", "IntValue", "LongValue", "DoubleValue", "StringValue", "ListValue", "MapValue", "AnyValueOneof", });
    internal_static_iquan_pb_AnyValueList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_iquan_pb_AnyValueList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_AnyValueList_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_iquan_pb_AnyValueMap_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_iquan_pb_AnyValueMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_AnyValueMap_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_iquan_pb_AnyValueMap_ValueEntry_descriptor =
      internal_static_iquan_pb_AnyValueMap_descriptor.getNestedTypes().get(0);
    internal_static_iquan_pb_AnyValueMap_ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_AnyValueMap_ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_iquan_pb_IdList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_iquan_pb_IdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_IdList_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_iquan_pb_PlanOp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_iquan_pb_PlanOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_PlanOp_descriptor,
        new java.lang.String[] { "Id", "OpName", "Inputs", "ReuseInputs", "Outputs", "Attrs", });
    internal_static_iquan_pb_PlanOp_InputsEntry_descriptor =
      internal_static_iquan_pb_PlanOp_descriptor.getNestedTypes().get(0);
    internal_static_iquan_pb_PlanOp_InputsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_PlanOp_InputsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_iquan_pb_PlanOp_AttrsEntry_descriptor =
      internal_static_iquan_pb_PlanOp_descriptor.getNestedTypes().get(1);
    internal_static_iquan_pb_PlanOp_AttrsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_PlanOp_AttrsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_iquan_pb_SqlPlan_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_iquan_pb_SqlPlan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_SqlPlan_descriptor,
        new java.lang.String[] { "RelPlanVersion", "RelPlan", "OptimizeInfos", "ExecParams", });
    internal_static_iquan_pb_SqlPlan_OptimizeInfosEntry_descriptor =
      internal_static_iquan_pb_SqlPlan_descriptor.getNestedTypes().get(0);
    internal_static_iquan_pb_SqlPlan_OptimizeInfosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_SqlPlan_OptimizeInfosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_iquan_pb_SqlPlan_ExecParamsEntry_descriptor =
      internal_static_iquan_pb_SqlPlan_descriptor.getNestedTypes().get(1);
    internal_static_iquan_pb_SqlPlan_ExecParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_SqlPlan_ExecParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_iquan_pb_SqlQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_iquan_pb_SqlQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_SqlQueryResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", "DebugInfos", "Result", });
    internal_static_iquan_pb_SqlQueryResponse_DebugInfosEntry_descriptor =
      internal_static_iquan_pb_SqlQueryResponse_descriptor.getNestedTypes().get(0);
    internal_static_iquan_pb_SqlQueryResponse_DebugInfosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iquan_pb_SqlQueryResponse_DebugInfosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
