// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iquan.proto

package com.taobao.search.iquan.client.common.pb;

public interface SqlPlanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iquan.pb.SqlPlan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rel_plan_version = 1;</code>
   */
  java.lang.String getRelPlanVersion();
  /**
   * <code>string rel_plan_version = 1;</code>
   */
  com.google.protobuf.ByteString
      getRelPlanVersionBytes();

  /**
   * <code>repeated .iquan.pb.PlanOp rel_plan = 2;</code>
   */
  java.util.List<com.taobao.search.iquan.client.common.pb.PlanOp> 
      getRelPlanList();
  /**
   * <code>repeated .iquan.pb.PlanOp rel_plan = 2;</code>
   */
  com.taobao.search.iquan.client.common.pb.PlanOp getRelPlan(int index);
  /**
   * <code>repeated .iquan.pb.PlanOp rel_plan = 2;</code>
   */
  int getRelPlanCount();
  /**
   * <code>repeated .iquan.pb.PlanOp rel_plan = 2;</code>
   */
  java.util.List<? extends com.taobao.search.iquan.client.common.pb.PlanOpOrBuilder> 
      getRelPlanOrBuilderList();
  /**
   * <code>repeated .iquan.pb.PlanOp rel_plan = 2;</code>
   */
  com.taobao.search.iquan.client.common.pb.PlanOpOrBuilder getRelPlanOrBuilder(
      int index);

  /**
   * <code>map&lt;string, .iquan.pb.AnyValue&gt; optimize_infos = 3;</code>
   */
  int getOptimizeInfosCount();
  /**
   * <code>map&lt;string, .iquan.pb.AnyValue&gt; optimize_infos = 3;</code>
   */
  boolean containsOptimizeInfos(
      java.lang.String key);
  /**
   * Use {@link #getOptimizeInfosMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.taobao.search.iquan.client.common.pb.AnyValue>
  getOptimizeInfos();
  /**
   * <code>map&lt;string, .iquan.pb.AnyValue&gt; optimize_infos = 3;</code>
   */
  java.util.Map<java.lang.String, com.taobao.search.iquan.client.common.pb.AnyValue>
  getOptimizeInfosMap();
  /**
   * <code>map&lt;string, .iquan.pb.AnyValue&gt; optimize_infos = 3;</code>
   */

  com.taobao.search.iquan.client.common.pb.AnyValue getOptimizeInfosOrDefault(
      java.lang.String key,
      com.taobao.search.iquan.client.common.pb.AnyValue defaultValue);
  /**
   * <code>map&lt;string, .iquan.pb.AnyValue&gt; optimize_infos = 3;</code>
   */

  com.taobao.search.iquan.client.common.pb.AnyValue getOptimizeInfosOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, string&gt; exec_params = 4;</code>
   */
  int getExecParamsCount();
  /**
   * <code>map&lt;string, string&gt; exec_params = 4;</code>
   */
  boolean containsExecParams(
      java.lang.String key);
  /**
   * Use {@link #getExecParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExecParams();
  /**
   * <code>map&lt;string, string&gt; exec_params = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExecParamsMap();
  /**
   * <code>map&lt;string, string&gt; exec_params = 4;</code>
   */

  java.lang.String getExecParamsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; exec_params = 4;</code>
   */

  java.lang.String getExecParamsOrThrow(
      java.lang.String key);
}
