package(default_visibility=['//aios/apps/facility/swift:__subpackages__'])
cc_library(
    name='swift_log_setup',
    srcs=glob(['LogSetup.cpp']),
    hdrs=glob(['LogSetup.h']),
    include_prefix='swift/tools',
    deps=['//aios/autil:log']
)
