# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

summary_sample_test_sources=  [
    'HighlightNumberExtractorTest.cpp',
    ]

libsname = ['summary_sample', 'ha3sdk_testlib', 'unittest', 'gmock', 'gtest']

env.aTest(target = 'summary_sample_test', 
          source = summary_sample_test_sources,
          LIBS = libsname + env['ha3_test_depend_lib'])
