# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

test_sources = Glob('*.cpp')

agg_test = env.aTest(target = 'builtin_agg_test',
                     source = test_sources,
                     LIBS = env['ha3_test_depend_lib']);
