# -*- mode: python -*-

Import('env')
env = env.Clone()

demo_table_src = [
    'demo_merge_policy.cpp',
    'demo_table_factory.cpp',
    'demo_table_merger.cpp',
    'demo_table_resource.cpp',
    'demo_table_writer.cpp',
    'demo_table_reader.cpp',
    'demo_building_segment_reader.cpp'
]

simple_demo_src = [
    'simple_merge_policy.cpp',
]

demoTableLib = env.aSharedLibrary(target = 'demoTable', source = demo_table_src)
simpleDemoLib = env.aLibrary(target = 'simpleTable', source = simple_demo_src)

demoTableInstalled = env.aCopy('#testdata', demoTableLib)

demo_cpps = [ demo_table_src ]
Return(['demo_cpps'] )

