load('//aios/storage:defs.bzl', 'strict_cc_library')
package(default_visibility=[':__subpackages__'])
strict_cc_library(
    name='attribute_field_format',
    srcs=[],
    hdrs=[],
    visibility=['//visibility:public'],
    deps=[
        '//aios/storage/indexlib/index/common/field_format/attribute:AttributeFieldPrinter',
        '//aios/storage/indexlib/index/common/field_format/attribute:attribute_convertor',
        '//aios/storage/indexlib/index/common/field_format/attribute:decoder',
        '//aios/storage/indexlib/index/common/field_format/attribute:type_info',
        '//aios/storage/indexlib/index/common/field_format/pack_attribute',
        '//aios/storage/indexlib/index/common/field_format/spatial:shape'
    ]
)
