# -*- mode: python -*-

Import('env')
env = env.Clone()

dictionary = env.aDirs('dictionary')
skiplist = env.aDirs('skiplist')

index_format_cpps = Glob('*.cpp')
formatcpps = [ dictionary, skiplist, index_format_cpps ]

#env.aLibrary(target='indexlib_indexformat', source=formatcpps)

# env.aDirs('test')
# env.aDirs('perf_test')

Return(['formatcpps'] )


