# -*- mode: python -*-

Import('env')

env = env.Clone()

common_test_sources=  [
    '#build_service/test/dotest.cpp',
    'PathDefineTest.cpp',
    'LocatorTest.cpp',
    'CounterFileSynchronizerTest.cpp',
    'CounterRedisSynchronizerTest.cpp',
    'CounterSynchronizerCreatorTest.cpp',
    'CounterSynchronizerTest.cpp',
    'ProcessorTaskIdentifierTest.cpp',
    ]

libsname = ['fake_redis_client', 'bs_common', 'proto_fake']

env.checkAllCppFileContained(Glob('*.cpp'), common_test_sources)

commontest = env.aTest(
    target = 'common_test',
    source = common_test_sources,
    LIBS = libsname + env['bs_test_common_lib'] + env['bs_worker_lib']
);
