# -*- mode: python -*-
import platform
Import('env')
env = env.Clone();

slice_list_ut_libs = [
    'indexlib_basic',
    'fslib-framework',
    'autil',
    'gmock',
    'gtest',
    'pthread'
]

slice_list_case_cpps=Glob('*_unittest.cpp')
slice_list_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    slice_list_case_cpps,
]

env.aTest(target = 'ie_slice_list_unittest',
          source = slice_list_ut_test_sources,
          LIBS= slice_list_ut_libs)

