# -*- mode: python -*-

Import('env')
env = env.Clone()

attribute_format_cpps=Glob('*.cpp')
#env.aLibrary(target='indexlib_attribute_format', source=attribute_format_cpps)

# env.aDirs('test')
# env.aDirs('perf_test')
Return(['attribute_format_cpps'] )


