load('//aios/storage:defs.bzl', 'strict_cc_library')
package(default_visibility=['//aios/storage/indexlib:__subpackages__'])
strict_cc_library(
    name='StringIndexMerger',
    srcs=[],
    deps=[
        '//aios/storage/indexlib/index/inverted_index/builtin_index/text:TextIndexMerger'
    ]
)
