load('//aios/storage/indexlib/index/ann/aitheta2:defs.bzl', 'aitheta_cc_test')
aitheta_cc_test(
    name='ANNPostingIteratorTest',
    srcs=['ANNPostingIteratorTest.cpp'],
    copts=['-fno-access-control'],
    data=[],
    deps=[
        '//aios/storage/indexlib/file_system',
        '//aios/storage/indexlib/index/ann:ANNPostingIterator',
        '//aios/unittest_framework'
    ]
)
