# -*- mode: python -*-

Import('env')
env = env.Clone()

document_reclaimer = env.aDirs('document_reclaimer')
merge_strategy = env.aDirs('merge_strategy')
split_strategy = env.aDirs('split_strategy')
merger_source=Glob('*.cpp')

mergercpps = [ merger_source, merge_strategy, split_strategy, document_reclaimer ]

env.aSharedLibrary(target='indexlib_merger', source=mergercpps)
env.aDirs('test')

Return(['mergercpps'] )


