package(default_visibility=['//aios/apps/facility/cm2:__subpackages__'])
cc_library(
    name='cm_server_base64',
    srcs=['base64.cpp'],
    hdrs=glob(['base64.h']),
    visibility=['//visibility:public'],
    deps=[]
)
