# -*- mode: python -*-

Import('env')

env = env.Clone()

libsummary_sources = [
    'DefaultSummaryExtractor.cpp',
    'SummaryProfile.cpp',
    'SummaryProfileManager.cpp',
    'SummaryProfileManagerCreator.cpp',
    'SummaryExtractorProvider.cpp',
    'SummaryExtractorChain.cpp',
    'CavaSummaryExtractor.cpp',
    ]

env.aLibrary(target = 'ha3_summary',
             source = libsummary_sources)

env.aDirs('test')
