load('//aios/storage:defs.bzl', 'strict_cc_library')
package(default_visibility=[':__subpackages__'])
strict_cc_library(
    name='constants',
    srcs=[],
    hdrs=[],
    visibility=['//aios/storage/indexlib:__subpackages__'],
    deps=[':Common', ':Constant', ':Types']
)
strict_cc_library(name='Common', srcs=[])
strict_cc_library(name='Types', srcs=[])
strict_cc_library(name='Constant', srcs=[])
