load('//aios/storage/indexlib:defs.bzl', 'indexlib_cc_library')
package(default_visibility=[':__subpackages__'])
indexlib_cc_library(
    name='constants',
    srcs=[],
    hdrs=[],
    visibility=['//aios/storage/indexlib:__subpackages__'],
    deps=[':Common', ':Constant', ':Types']
)
indexlib_cc_library(name='Common', srcs=[])
indexlib_cc_library(name='Types', srcs=[])
indexlib_cc_library(name='Constant', srcs=[])
