# -*- mode: python -*-

Import('env')
env = env.Clone()

document_tokenize_ut_libs = [
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
]

document_tokenize_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    'tokenize_field_unittest.cpp',
    'tokenize_section_unittest.cpp',
    'tokenize_document_unittest.cpp',
]

env.aTest(target = 'indexlib_document_tokenize_unittest',
          source = document_tokenize_ut_test_sources,
          LIBS = document_tokenize_ut_libs)
