#!/bin/sh
params=$*
cmd=$0
cmd_parent_dir=${cmd%local_script_runner}
if [ $cmd_parent_dir = "./" ]; then
    cmd_parent_dir=`pwd`"/"
fi
local_script_runner_libpath=${cmd_parent_dir}../lib64:${cmd_parent_dir}../../lib64:${cmd_parent_dir}../lib:${cmd_parent_dir}../../lib
class_path_util=${cmd_parent_dir}../bin/class_path_util

if [ ! -f $class_path_util ];then
    echo "$class_path_util not exist"
    exit -1
fi

if [ "$JAVA_HOME" != "" ];then
    jvm_lib_path=$JAVA_HOME/jre/lib/amd64/server/
fi

export LD_LIBRARY_PATH=$local_script_runner_libpath:$LD_LIBRARY_PATH:$jvm_lib_path:/usr/ali/java/jre/lib/amd64/server/
local_script_runner_bin_cmd=${cmd_parent_dir}local_script_runner_bin
if [ -f ${local_script_runner_bin_cmd} ]; then
    ${local_script_runner_bin_cmd} $params
else
    echo "cannot find local_script_runner_bin in "$cmd_parent_dir >&2
    exit 10
fi

exit $?
