# -*- mode: python -*-

Import('env')

env = env.Clone()

scan_sources = Glob('*.cpp') + Glob('*.yy') + Glob('*.ll')

env.SideEffect(['SpQueryParser.hh', 'location.hh', 'position.hh',  'stack.hh'], ['SpQueryParser.cc'])

env.aDirs('test')

Return(['scan_sources'])
