# -*- mode: python -*-

Import('env')
env = env.Clone()

indexdoc=Glob('*.cpp')
normaldoc=env.aDirs('normal_document')
kvdoc=env.aDirs('kv_document')

#env.aDirs('test')

index_document_cpps = [ indexdoc, normaldoc, kvdoc ]
Return(['index_document_cpps'])
