# -*- mode: python -*-

Import('env')
env = env.Clone()
source = Glob('*.cpp')

depend_libs = []

env.aLibrary(
    target='ha3_sql_data',
    LIBS = depend_libs,
    source = source)

env.aDirs('test')

Return('source')
