# -*- mode: python -*-

Import('env')
env = env.Clone()
if ARGUMENTS.get('debug', False):
    env.Append(CCFLAGS = '-DENABLE_PERF_TEST')
aitheta = env.aDirs('aitheta')
plugincpps = [aitheta]
Return(['plugincpps'])
