# -*- mode: python -*-

Import('env')
env = env.Clone()

remote_access_source=Glob('*.cpp')

#env.aLibrary(target='indexlib_remote_access', source=remote_access_source)

env.aDirs('test')
Return(['remote_access_source'] )
