# -*- mode: python -*-

Import('env')

env = env.Clone()

librank_sources =  [
    'ComboComparator.cpp',
    'Comparator.cpp',
    'DefaultScorer.cpp',
    'DistinctComparator.cpp',
    'DistinctHitCollector.cpp',
    'DistinctInfo.cpp',
    'DistinctMap.cpp',
    'GlobalMatchData.cpp',
    'HitCollector.cpp',
    'MatchData.cpp',
    'MatchDocPriorityQueue.cpp',
    'MetaInfo.cpp',
    'RankProfile.cpp',
    'RankProfileManagerCreator.cpp',
    'RankProfileManager.cpp',
    'RecordInfoScorer.cpp',
    'ScoringProvider.cpp',
    'SimpleDistinctBoostScorer.cpp',
    'TermMatchData.cpp',
    'TermMetaInfo.cpp',
    'GeneralScorer.cpp',
    'TestScorer.cpp',
    'GradeComparator.cpp',
    'AttributeExpressionConvertor.cpp',
    'SeekPositionScorer.cpp',
    'ComparatorCreator.cpp',
    'HitCollectorBase.cpp',
    'MultiHitCollector.cpp',
    'DistinctPriorityQueue.cpp',
    'NthElementCollector.cpp',
    'SimpleMatchData.cpp',
    'CavaScorerAdapter.cpp',
    ]

env.aLibrary(target = 'ha3_rank',
             source = librank_sources)

env.aDirs('test')
