# -*- mode: python -*-

Import('env')
env = env.Clone()

env.aDirs('test')
env.aDirs('perf_test')

util_hash_table=Glob('*.cpp')

#env.aLibrary(target='util_hash_table', source=util_hash_table)

Return(['util_hash_table'])
