load('//aios/storage:defs.bzl', 'strict_cc_library')
package(
    default_visibility=[
        '//aios/storage/indexlib/table/normal_table:__subpackages__'
    ]
)
strict_cc_library(
    name='SegmentGroupConfig',
    deps=[
        '//aios/autil:json',
        '//aios/storage/indexlib/index/attribute/expression:config'
    ]
)
