# -*- mode: python -*-

Import('env')
env = env.Clone()

operation_queue_perf_test_sources_for_gtest = [
    '#indexlib/test/dotest.cpp',
    'operation_iterator_unittest.cpp',
    'operation_writer_perf_unittest.cpp',
]

operation_queue_perf_libs = [
    'indexlib_test',
    'indexlib_indextest_common',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'fslib-framework',
    'gmock',
    'gtest',
]

env.aTest(target = 'indexlib_operation_queue_perftest_for_gtest', 
          source = operation_queue_perf_test_sources_for_gtest,
          LIBS = operation_queue_perf_libs)


