# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

libfunc_expression_sources = [
    'FunctionProvider.cpp',
    ]


env.aLibrary(target = 'ha3_func_expression',
             source = libfunc_expression_sources)

# List my sub-directories.
env.aDirs('test')
