# -*- mode: python -*-

Import('env')
env = env.Clone()
source = Glob('*.cpp')
env.aLibrary(
    target='ha3_suez_turing_agg_ops',
    source = source)

env.aLibraryAndInstall(
    target='ha3_suez_turing_agg_opdef',
    source=['OpDefs.cpp'])
env.aDirs('test')
