package(default_visibility=['//aios/sql/iquan/cpp:__subpackages__'])
filegroup(
    name='test_alog_conf', testonly=True, srcs=glob(['misc/test_alog.conf'])
)
filegroup(name='leak_suppression', srcs=glob(['misc/leak_suppression']))
