# -*- mode: python -*-

Import('env')
env = env.Clone()

util_hash_table_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
#    'dense_hash_table_unittest.cpp',
#    'cuckoo_hash_table_unittest.cpp',
    'chain_hash_table_unittest.cpp',
    'hash_table_writer_unittest.cpp',
    'hash_table_reader_unittest.cpp',
    'separate_chain_hash_table_unittest.cpp',
]

env.aTest(target = 'indexlib_util_hash_table_unittest',
          source = util_hash_table_ut_test_sources,
          LIBS= ['indexlib_basic', 'autil', 'gmock', 'gtest'])
