# -*- mode: python -*-

Import('env')
env = env.Clone()

open_executor_source=Glob('*.cpp')

#env.aLibrary(target='indexlib_open_executor', source=open_executor_source)

env.aDirs('test')
Return(['open_executor_source'] )
