# -*- mode: python -*-

Import('env')

env = env.Clone()
source = Glob('*.cpp')

depend_libs = ['tensorflow_cc']
env.aLibrary(
    target = 'ha3_sql_framework',
    LIBS = depend_libs,
    source = source)

env.aDirs('test')

Return('source')
