# -*- mode: python -*-

Import('env')
env = env.Clone()

patch_test_sources = [
    '#indexlib/test/dotest.cpp',
    'partition_patch_meta_unittest.cpp',
    'partition_patch_meta_creator_unittest.cpp',
    'partition_patch_index_accessor_unittest.cpp',
    'single_part_patch_finder_unittest.cpp',
    'multi_part_patch_finder_unittest.cpp',
]

patch_libs = [
    'indexlib_indextest_common',
    'indexlib_file_system_test_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
]

env.aTest(target = 'ie_partition_data_patch_unittest', 
          source = patch_test_sources, LIBS = patch_libs)
