// automatically generated by the FlatBuffers compiler, do not modify

package com.taobao.search.iquan.client.common.fb;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class IquanFbBool extends Table {
  public static IquanFbBool getRootAsIquanFbBool(ByteBuffer _bb) { return getRootAsIquanFbBool(_bb, new IquanFbBool()); }
  public static IquanFbBool getRootAsIquanFbBool(ByteBuffer _bb, IquanFbBool obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public IquanFbBool __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean value() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createIquanFbBool(FlatBufferBuilder builder,
      boolean value) {
    builder.startObject(1);
    IquanFbBool.addValue(builder, value);
    return IquanFbBool.endIquanFbBool(builder);
  }

  public static void startIquanFbBool(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, boolean value) { builder.addBoolean(0, value, false); }
  public static int endIquanFbBool(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

