// automatically generated by the FlatBuffers compiler, do not modify

package com.taobao.search.iquan.client.common.fb;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class IquanFbString extends Table {
  public static IquanFbString getRootAsIquanFbString(ByteBuffer _bb) { return getRootAsIquanFbString(_bb, new IquanFbString()); }
  public static IquanFbString getRootAsIquanFbString(ByteBuffer _bb, IquanFbString obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public IquanFbString __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String value() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createIquanFbString(FlatBufferBuilder builder,
      int valueOffset) {
    builder.startObject(1);
    IquanFbString.addValue(builder, valueOffset);
    return IquanFbString.endIquanFbString(builder);
  }

  public static void startIquanFbString(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int endIquanFbString(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

