// automatically generated by the FlatBuffers compiler, do not modify

package com.taobao.search.iquan.client.common.fb;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class IquanFbSqlQueryResponse extends Table {
  public static IquanFbSqlQueryResponse getRootAsIquanFbSqlQueryResponse(ByteBuffer _bb) { return getRootAsIquanFbSqlQueryResponse(_bb, new IquanFbSqlQueryResponse()); }
  public static IquanFbSqlQueryResponse getRootAsIquanFbSqlQueryResponse(ByteBuffer _bb, IquanFbSqlQueryResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public IquanFbSqlQueryResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int errorCode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String errorMsg() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorMsgAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer errorMsgInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public IquanFbSqlPlan result() { return result(new IquanFbSqlPlan()); }
  public IquanFbSqlPlan result(IquanFbSqlPlan obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createIquanFbSqlQueryResponse(FlatBufferBuilder builder,
      int error_code,
      int error_msgOffset,
      int resultOffset) {
    builder.startObject(3);
    IquanFbSqlQueryResponse.addResult(builder, resultOffset);
    IquanFbSqlQueryResponse.addErrorMsg(builder, error_msgOffset);
    IquanFbSqlQueryResponse.addErrorCode(builder, error_code);
    return IquanFbSqlQueryResponse.endIquanFbSqlQueryResponse(builder);
  }

  public static void startIquanFbSqlQueryResponse(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addErrorCode(FlatBufferBuilder builder, int errorCode) { builder.addInt(0, errorCode, 0); }
  public static void addErrorMsg(FlatBufferBuilder builder, int errorMsgOffset) { builder.addOffset(1, errorMsgOffset, 0); }
  public static void addResult(FlatBufferBuilder builder, int resultOffset) { builder.addOffset(2, resultOffset, 0); }
  public static int endIquanFbSqlQueryResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishIquanFbSqlQueryResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedIquanFbSqlQueryResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

