# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

env.Append(LIBS=['dl'])

util_perftest_sources=  [
    '#ha3/test/dotest.cpp',
    'ObjectAllocatorPerfTest.cpp',
    ]

utilperftest = env.aTest(target = 'util_perftest',
                         source = util_perftest_sources,
                         LIBS = ['ha3_util', 'autil', 'mxml']
                         );
