# -*- mode: python -*-

Import('env')
env = env.Clone()

segment_test_sources = [
    '#indexlib/test/dotest.cpp',
    'segment_directory_unittest.cpp',
    'join_segment_directory_unittest.cpp',
    'multi_part_segment_directory_unittest.cpp',
    'online_segment_directory_unittest.cpp',
    'parallel_offline_segment_directory_unittest.cpp',
    'in_memory_segment_unittest.cpp',
    'partition_segment_iterator_unittest.cpp',
    'built_segment_iterator_unittest.cpp',
    'building_segment_iterator_unittest.cpp',
]

segment_libs = [
    'indexlib_indextest_common',
    'indexlib_file_system_test_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
]

env.aTest(target = 'ie_partiton_data_segment_unittest', 
          source = segment_test_sources, LIBS = segment_libs)

