package(default_visibility=['//aios/ha3:__subpackages__'])
cc_library(
    name='sql_ops_sort_init_param',
    srcs=glob(['*.cpp']),
    hdrs=glob(['*.h']),
    deps=['//aios/ha3/ha3/sql/ops/calc:sql_ops_calc_table'],
    include_prefix='ha3/sql/ops/sort'
)
