// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: swift/protocol/ErrCode.proto

package com.alibaba.search.swift.protocol;

public final class ErrCode {
  private ErrCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code swift.protocol.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR_NONE = 0;</code>
     *
     * <pre>
     *&#47;//////////////////////////////
     *        COMMON X00XX
     * ///////////////////////////////
     * </pre>
     */
    ERROR_NONE(0, 0),
    /**
     * <code>ERROR_UNKNOWN = 1;</code>
     */
    ERROR_UNKNOWN(1, 1),
    /**
     * <code>ERROR_INFO_START = 10000;</code>
     */
    ERROR_INFO_START(2, 10000),
    /**
     * <code>ERROR_WARN_START = 20000;</code>
     */
    ERROR_WARN_START(3, 20000),
    /**
     * <code>ERROR_FATAL_START = 30000;</code>
     */
    ERROR_FATAL_START(4, 30000),
    /**
     * <code>ERROR_WORKER_DEAD = 30002;</code>
     */
    ERROR_WORKER_DEAD(5, 30002),
    /**
     * <code>ERROR_DECOMPRESS_MESSAGE = 3004;</code>
     */
    ERROR_DECOMPRESS_MESSAGE(6, 3004),
    /**
     * <code>ERROR_ADMIN_TOPIC_HAS_EXISTED = 21101;</code>
     *
     * <pre>
     *&#47;//////////////////////////////
     *        ADMIN ERROR X1XXX
     * ///////////////////////////////
     * USER ERROR X11XX
     * </pre>
     */
    ERROR_ADMIN_TOPIC_HAS_EXISTED(7, 21101),
    /**
     * <code>ERROR_ADMIN_TOPIC_NOT_EXISTED = 21102;</code>
     */
    ERROR_ADMIN_TOPIC_NOT_EXISTED(8, 21102),
    /**
     * <code>ERROR_ADMIN_INVALID_PARAMETER = 21103;</code>
     */
    ERROR_ADMIN_INVALID_PARAMETER(9, 21103),
    /**
     * <code>ERROR_ADMIN_NOT_LEADER = 21104;</code>
     */
    ERROR_ADMIN_NOT_LEADER(10, 21104),
    /**
     * <code>ERROR_ADMIN_PARTITION_NOT_EXISTED = 21105;</code>
     */
    ERROR_ADMIN_PARTITION_NOT_EXISTED(11, 21105),
    /**
     * <code>ERROR_ADMIN_UNKNOWN_COMMAND = 21106;</code>
     */
    ERROR_ADMIN_UNKNOWN_COMMAND(12, 21106),
    /**
     * <code>ERROR_ADMIN_IP_SET_INVALID = 21107;</code>
     */
    ERROR_ADMIN_IP_SET_INVALID(13, 21107),
    /**
     * <code>ERROR_ADMIN_INVALID_CONFIG = 21108;</code>
     */
    ERROR_ADMIN_INVALID_CONFIG(14, 21108),
    /**
     * <code>ERROR_BROKER_IS_UPGRADING = 21109;</code>
     */
    ERROR_BROKER_IS_UPGRADING(15, 21109),
    /**
     * <code>ERROR_UPGRADE_BROKER_BEFORE_ADMIN = 21110;</code>
     */
    ERROR_UPGRADE_BROKER_BEFORE_ADMIN(16, 21110),
    /**
     * <code>ERROR_WRITE_BROKER_TARGET_VERSION = 21111;</code>
     */
    ERROR_WRITE_BROKER_TARGET_VERSION(17, 21111),
    /**
     * <code>ERROR_UPGRADE_VERSION_SAME_AS_CURRENT = 21112;</code>
     */
    ERROR_UPGRADE_VERSION_SAME_AS_CURRENT(18, 21112),
    /**
     * <code>ERROR_ADMIN_APPLICATION_ID_CHANGED = 21113;</code>
     */
    ERROR_ADMIN_APPLICATION_ID_CHANGED(19, 21113),
    /**
     * <code>ERROR_CONFIG_IS_ROLLBACKING = 21114;</code>
     */
    ERROR_CONFIG_IS_ROLLBACKING(20, 21114),
    /**
     * <code>ERROR_NOT_NEED_ROLLBACK = 21115;</code>
     */
    ERROR_NOT_NEED_ROLLBACK(21, 21115),
    /**
     * <code>ERROR_WRITE_ROLLBACK_FILE = 21116;</code>
     */
    ERROR_WRITE_ROLLBACK_FILE(22, 21116),
    /**
     * <code>ERROR_UPGRADE_ROLE_VERSION = 21117;</code>
     */
    ERROR_UPGRADE_ROLE_VERSION(23, 21117),
    /**
     * <code>ERROR_ADMIN_NOT_ENOUGH_RESOURCE = 21201;</code>
     *
     * <pre>
     * SYS ERROR X12XX
     * </pre>
     */
    ERROR_ADMIN_NOT_ENOUGH_RESOURCE(24, 21201),
    /**
     * <code>ERROR_ADMIN_OPERATION_FAILED = 21202;</code>
     */
    ERROR_ADMIN_OPERATION_FAILED(25, 21202),
    /**
     * <code>ERROR_ADMIN_CLEAR_OLD_TOPIC_DATA_FAILED = 21203;</code>
     */
    ERROR_ADMIN_CLEAR_OLD_TOPIC_DATA_FAILED(26, 21203),
    /**
     * <code>ERROR_ADMIN_SYS_NOT_INIT = 31201;</code>
     */
    ERROR_ADMIN_SYS_NOT_INIT(27, 31201),
    /**
     * <code>ERROR_ADMIN_NOT_IMPLEMENTED = 31202;</code>
     */
    ERROR_ADMIN_NOT_IMPLEMENTED(28, 31202),
    /**
     * <code>ERROR_BROKER_FAIL = 12101;</code>
     *
     * <pre>
     *&#47;//////////////////////////////
     *       BROKER ERROR X2XXX
     * ///////////////////////////////
     * USER ERROR X21XX
     * </pre>
     */
    ERROR_BROKER_FAIL(29, 12101),
    /**
     * <code>ERROR_BROKER_STOPPED = 12102;</code>
     */
    ERROR_BROKER_STOPPED(30, 12102),
    /**
     * <code>ERROR_BROKER_BUSY = 12103;</code>
     */
    ERROR_BROKER_BUSY(31, 12103),
    /**
     * <code>ERROR_BROKER_TOPIC_PARTITION_NOT_FOUND = 12104;</code>
     */
    ERROR_BROKER_TOPIC_PARTITION_NOT_FOUND(32, 12104),
    /**
     * <code>ERROR_BROKER_TOPIC_PARTITION_NOT_RUNNING = 12105;</code>
     */
    ERROR_BROKER_TOPIC_PARTITION_NOT_RUNNING(33, 12105),
    /**
     * <code>ERROR_BROKER_REQUEST_INVALID = 12106;</code>
     */
    ERROR_BROKER_REQUEST_INVALID(34, 12106),
    /**
     * <code>ERROR_BROKER_NO_DATA = 12107;</code>
     *
     * <pre>
     * getMessage, getMaxMessageId
     * </pre>
     */
    ERROR_BROKER_NO_DATA(35, 12107),
    /**
     * <code>ERROR_BROKER_TOPIC_NOT_SUPPORT_FIELD_FILTER = 12108;</code>
     */
    ERROR_BROKER_TOPIC_NOT_SUPPORT_FIELD_FILTER(36, 12108),
    /**
     * <code>ERROR_BROKER_INIT_FIELD_FILTER_FAILD = 12109;</code>
     */
    ERROR_BROKER_INIT_FIELD_FILTER_FAILD(37, 12109),
    /**
     * <code>ERROR_BROKER_SESSION_CHANGED = 12110;</code>
     */
    ERROR_BROKER_SESSION_CHANGED(38, 12110),
    /**
     * <code>ERROR_BROKER_SOME_MESSAGE_LOST = 22101;</code>
     *
     * <pre>
     * getMessage
     * </pre>
     */
    ERROR_BROKER_SOME_MESSAGE_LOST(39, 22101),
    /**
     * <code>ERROR_BROKER_MSG_LENGTH_EXCEEDED = 22102;</code>
     *
     * <pre>
     * sendMessage
     * </pre>
     */
    ERROR_BROKER_MSG_LENGTH_EXCEEDED(40, 22102),
    /**
     * <code>ERROR_BROKER_TIMESTAMP_TOO_LATEST = 22103;</code>
     *
     * <pre>
     * getMinMessageIdByTime
     * </pre>
     */
    ERROR_BROKER_TIMESTAMP_TOO_LATEST(41, 22103),
    /**
     * <code>ERROR_BROKER_MESSAGE_FORMAT_INVALID = 22104;</code>
     */
    ERROR_BROKER_MESSAGE_FORMAT_INVALID(42, 22104),
    /**
     * <code>ERROR_BROKER_REPEATED_ADD_TOPIC_PARTITION = 22201;</code>
     *
     * <pre>
     * SYS ERROR X22XX
     * </pre>
     */
    ERROR_BROKER_REPEATED_ADD_TOPIC_PARTITION(43, 22201),
    /**
     * <code>ERROR_BROKER_OPEN_FILE = 22202;</code>
     */
    ERROR_BROKER_OPEN_FILE(44, 22202),
    /**
     * <code>ERROR_BROKER_WRITE_FILE = 22203;</code>
     */
    ERROR_BROKER_WRITE_FILE(45, 22203),
    /**
     * <code>ERROR_BROKER_COMMIT_FILE = 22204;</code>
     */
    ERROR_BROKER_COMMIT_FILE(46, 22204),
    /**
     * <code>ERROR_BROKER_CLOSE_FILE = 22205;</code>
     */
    ERROR_BROKER_CLOSE_FILE(47, 22205),
    /**
     * <code>ERROR_BROKER_READ_FILE = 22206;</code>
     */
    ERROR_BROKER_READ_FILE(48, 22206),
    /**
     * <code>ERROR_BROKER_FS_OPERATE = 22207;</code>
     */
    ERROR_BROKER_FS_OPERATE(49, 22207),
    /**
     * <code>ERROR_BROKER_NO_DATA_IN_MEM = 22211;</code>
     */
    ERROR_BROKER_NO_DATA_IN_MEM(50, 22211),
    /**
     * <code>ERROR_BROKER_RECOVER_FILE_MESSAGE_NO_MORE_MEMORY = 22212;</code>
     */
    ERROR_BROKER_RECOVER_FILE_MESSAGE_NO_MORE_MEMORY(51, 22212),
    /**
     * <code>ERROR_BROKER_CREATE_THREAD = 32201;</code>
     */
    ERROR_BROKER_CREATE_THREAD(52, 32201),
    /**
     * <code>ERROR_BROKER_MKDIR = 32202;</code>
     */
    ERROR_BROKER_MKDIR(53, 32202),
    /**
     * <code>ERROR_BROKER_DATA_DIR_EMPTY = 32203;</code>
     */
    ERROR_BROKER_DATA_DIR_EMPTY(54, 32203),
    /**
     * <code>ERROR_CLIENT_INIT_TWICE = 13201;</code>
     *
     * <pre>
     *&#47;////////////////////////////////
     *       CLIENT ERROR X3XXX
     * /////////////////////////////////
     * SYS ERROR X32XX
     * </pre>
     */
    ERROR_CLIENT_INIT_TWICE(55, 13201),
    /**
     * <code>ERROR_CLIENT_INIT_INVALID_PARAMETERS = 13202;</code>
     */
    ERROR_CLIENT_INIT_INVALID_PARAMETERS(56, 13202),
    /**
     * <code>ERROR_CLIENT_RPC_CONNECT = 13203;</code>
     */
    ERROR_CLIENT_RPC_CONNECT(57, 13203),
    /**
     * <code>ERROR_CLIENT_GET_ADMIN_INFO_FAILED = 13204;</code>
     */
    ERROR_CLIENT_GET_ADMIN_INFO_FAILED(58, 13204),
    /**
     * <code>ERROR_CLIENT_GET_BROKER_ADDRESS_FAILED = 13205;</code>
     */
    ERROR_CLIENT_GET_BROKER_ADDRESS_FAILED(59, 13205),
    /**
     * <code>ERROR_CLIENT_INVALID_RESPONSE = 13206;</code>
     */
    ERROR_CLIENT_INVALID_RESPONSE(60, 13206),
    /**
     * <code>ERROR_CLIENT_SYS_STOPPED = 13207;</code>
     */
    ERROR_CLIENT_SYS_STOPPED(61, 13207),
    /**
     * <code>ERROR_CLIENT_ARPC_ERROR = 13208;</code>
     */
    ERROR_CLIENT_ARPC_ERROR(62, 13208),
    /**
     * <code>ERROR_CLIENT_READ_MESSAGE_TIMEOUT = 13209;</code>
     */
    ERROR_CLIENT_READ_MESSAGE_TIMEOUT(63, 13209),
    /**
     * <code>ERROR_CLIENT_SEND_BUFFER_FULL = 13210;</code>
     */
    ERROR_CLIENT_SEND_BUFFER_FULL(64, 13210),
    /**
     * <code>ERROR_CLIENT_SOME_MESSAGE_SEND_FAILED = 13211;</code>
     */
    ERROR_CLIENT_SOME_MESSAGE_SEND_FAILED(65, 13211),
    /**
     * <code>ERROR_CLIENT_INIT_FAILED = 13212;</code>
     */
    ERROR_CLIENT_INIT_FAILED(66, 13212),
    /**
     * <code>ERROR_CLIENT_NO_MORE_MESSAGE = 13213;</code>
     */
    ERROR_CLIENT_NO_MORE_MESSAGE(67, 13213),
    /**
     * <code>ERROR_CLIENT_INVALID_PARAMETERS = 13214;</code>
     */
    ERROR_CLIENT_INVALID_PARAMETERS(68, 13214),
    /**
     * <code>ERROR_CLIENT_NOT_INITED = 13215;</code>
     */
    ERROR_CLIENT_NOT_INITED(69, 13215),
    /**
     * <code>ERROR_CLIENT_INVALID_PARTITIONID = 13216;</code>
     */
    ERROR_CLIENT_INVALID_PARTITIONID(70, 13216),
    /**
     * <code>ERROR_CLIENT_EOF = 13217;</code>
     */
    ERROR_CLIENT_EOF(71, 13217),
    /**
     * <code>ERROR_CLIENT_EXCEED_TIME_STAMP_LIMIT = 13219;</code>
     */
    ERROR_CLIENT_EXCEED_TIME_STAMP_LIMIT(72, 13219),
    ;

    /**
     * <code>ERROR_NONE = 0;</code>
     *
     * <pre>
     *&#47;//////////////////////////////
     *        COMMON X00XX
     * ///////////////////////////////
     * </pre>
     */
    public static final int ERROR_NONE_VALUE = 0;
    /**
     * <code>ERROR_UNKNOWN = 1;</code>
     */
    public static final int ERROR_UNKNOWN_VALUE = 1;
    /**
     * <code>ERROR_INFO_START = 10000;</code>
     */
    public static final int ERROR_INFO_START_VALUE = 10000;
    /**
     * <code>ERROR_WARN_START = 20000;</code>
     */
    public static final int ERROR_WARN_START_VALUE = 20000;
    /**
     * <code>ERROR_FATAL_START = 30000;</code>
     */
    public static final int ERROR_FATAL_START_VALUE = 30000;
    /**
     * <code>ERROR_WORKER_DEAD = 30002;</code>
     */
    public static final int ERROR_WORKER_DEAD_VALUE = 30002;
    /**
     * <code>ERROR_DECOMPRESS_MESSAGE = 3004;</code>
     */
    public static final int ERROR_DECOMPRESS_MESSAGE_VALUE = 3004;
    /**
     * <code>ERROR_ADMIN_TOPIC_HAS_EXISTED = 21101;</code>
     *
     * <pre>
     *&#47;//////////////////////////////
     *        ADMIN ERROR X1XXX
     * ///////////////////////////////
     * USER ERROR X11XX
     * </pre>
     */
    public static final int ERROR_ADMIN_TOPIC_HAS_EXISTED_VALUE = 21101;
    /**
     * <code>ERROR_ADMIN_TOPIC_NOT_EXISTED = 21102;</code>
     */
    public static final int ERROR_ADMIN_TOPIC_NOT_EXISTED_VALUE = 21102;
    /**
     * <code>ERROR_ADMIN_INVALID_PARAMETER = 21103;</code>
     */
    public static final int ERROR_ADMIN_INVALID_PARAMETER_VALUE = 21103;
    /**
     * <code>ERROR_ADMIN_NOT_LEADER = 21104;</code>
     */
    public static final int ERROR_ADMIN_NOT_LEADER_VALUE = 21104;
    /**
     * <code>ERROR_ADMIN_PARTITION_NOT_EXISTED = 21105;</code>
     */
    public static final int ERROR_ADMIN_PARTITION_NOT_EXISTED_VALUE = 21105;
    /**
     * <code>ERROR_ADMIN_UNKNOWN_COMMAND = 21106;</code>
     */
    public static final int ERROR_ADMIN_UNKNOWN_COMMAND_VALUE = 21106;
    /**
     * <code>ERROR_ADMIN_IP_SET_INVALID = 21107;</code>
     */
    public static final int ERROR_ADMIN_IP_SET_INVALID_VALUE = 21107;
    /**
     * <code>ERROR_ADMIN_INVALID_CONFIG = 21108;</code>
     */
    public static final int ERROR_ADMIN_INVALID_CONFIG_VALUE = 21108;
    /**
     * <code>ERROR_BROKER_IS_UPGRADING = 21109;</code>
     */
    public static final int ERROR_BROKER_IS_UPGRADING_VALUE = 21109;
    /**
     * <code>ERROR_UPGRADE_BROKER_BEFORE_ADMIN = 21110;</code>
     */
    public static final int ERROR_UPGRADE_BROKER_BEFORE_ADMIN_VALUE = 21110;
    /**
     * <code>ERROR_WRITE_BROKER_TARGET_VERSION = 21111;</code>
     */
    public static final int ERROR_WRITE_BROKER_TARGET_VERSION_VALUE = 21111;
    /**
     * <code>ERROR_UPGRADE_VERSION_SAME_AS_CURRENT = 21112;</code>
     */
    public static final int ERROR_UPGRADE_VERSION_SAME_AS_CURRENT_VALUE = 21112;
    /**
     * <code>ERROR_ADMIN_APPLICATION_ID_CHANGED = 21113;</code>
     */
    public static final int ERROR_ADMIN_APPLICATION_ID_CHANGED_VALUE = 21113;
    /**
     * <code>ERROR_CONFIG_IS_ROLLBACKING = 21114;</code>
     */
    public static final int ERROR_CONFIG_IS_ROLLBACKING_VALUE = 21114;
    /**
     * <code>ERROR_NOT_NEED_ROLLBACK = 21115;</code>
     */
    public static final int ERROR_NOT_NEED_ROLLBACK_VALUE = 21115;
    /**
     * <code>ERROR_WRITE_ROLLBACK_FILE = 21116;</code>
     */
    public static final int ERROR_WRITE_ROLLBACK_FILE_VALUE = 21116;
    /**
     * <code>ERROR_UPGRADE_ROLE_VERSION = 21117;</code>
     */
    public static final int ERROR_UPGRADE_ROLE_VERSION_VALUE = 21117;
    /**
     * <code>ERROR_ADMIN_NOT_ENOUGH_RESOURCE = 21201;</code>
     *
     * <pre>
     * SYS ERROR X12XX
     * </pre>
     */
    public static final int ERROR_ADMIN_NOT_ENOUGH_RESOURCE_VALUE = 21201;
    /**
     * <code>ERROR_ADMIN_OPERATION_FAILED = 21202;</code>
     */
    public static final int ERROR_ADMIN_OPERATION_FAILED_VALUE = 21202;
    /**
     * <code>ERROR_ADMIN_CLEAR_OLD_TOPIC_DATA_FAILED = 21203;</code>
     */
    public static final int ERROR_ADMIN_CLEAR_OLD_TOPIC_DATA_FAILED_VALUE = 21203;
    /**
     * <code>ERROR_ADMIN_SYS_NOT_INIT = 31201;</code>
     */
    public static final int ERROR_ADMIN_SYS_NOT_INIT_VALUE = 31201;
    /**
     * <code>ERROR_ADMIN_NOT_IMPLEMENTED = 31202;</code>
     */
    public static final int ERROR_ADMIN_NOT_IMPLEMENTED_VALUE = 31202;
    /**
     * <code>ERROR_BROKER_FAIL = 12101;</code>
     *
     * <pre>
     *&#47;//////////////////////////////
     *       BROKER ERROR X2XXX
     * ///////////////////////////////
     * USER ERROR X21XX
     * </pre>
     */
    public static final int ERROR_BROKER_FAIL_VALUE = 12101;
    /**
     * <code>ERROR_BROKER_STOPPED = 12102;</code>
     */
    public static final int ERROR_BROKER_STOPPED_VALUE = 12102;
    /**
     * <code>ERROR_BROKER_BUSY = 12103;</code>
     */
    public static final int ERROR_BROKER_BUSY_VALUE = 12103;
    /**
     * <code>ERROR_BROKER_TOPIC_PARTITION_NOT_FOUND = 12104;</code>
     */
    public static final int ERROR_BROKER_TOPIC_PARTITION_NOT_FOUND_VALUE = 12104;
    /**
     * <code>ERROR_BROKER_TOPIC_PARTITION_NOT_RUNNING = 12105;</code>
     */
    public static final int ERROR_BROKER_TOPIC_PARTITION_NOT_RUNNING_VALUE = 12105;
    /**
     * <code>ERROR_BROKER_REQUEST_INVALID = 12106;</code>
     */
    public static final int ERROR_BROKER_REQUEST_INVALID_VALUE = 12106;
    /**
     * <code>ERROR_BROKER_NO_DATA = 12107;</code>
     *
     * <pre>
     * getMessage, getMaxMessageId
     * </pre>
     */
    public static final int ERROR_BROKER_NO_DATA_VALUE = 12107;
    /**
     * <code>ERROR_BROKER_TOPIC_NOT_SUPPORT_FIELD_FILTER = 12108;</code>
     */
    public static final int ERROR_BROKER_TOPIC_NOT_SUPPORT_FIELD_FILTER_VALUE = 12108;
    /**
     * <code>ERROR_BROKER_INIT_FIELD_FILTER_FAILD = 12109;</code>
     */
    public static final int ERROR_BROKER_INIT_FIELD_FILTER_FAILD_VALUE = 12109;
    /**
     * <code>ERROR_BROKER_SESSION_CHANGED = 12110;</code>
     */
    public static final int ERROR_BROKER_SESSION_CHANGED_VALUE = 12110;
    /**
     * <code>ERROR_BROKER_SOME_MESSAGE_LOST = 22101;</code>
     *
     * <pre>
     * getMessage
     * </pre>
     */
    public static final int ERROR_BROKER_SOME_MESSAGE_LOST_VALUE = 22101;
    /**
     * <code>ERROR_BROKER_MSG_LENGTH_EXCEEDED = 22102;</code>
     *
     * <pre>
     * sendMessage
     * </pre>
     */
    public static final int ERROR_BROKER_MSG_LENGTH_EXCEEDED_VALUE = 22102;
    /**
     * <code>ERROR_BROKER_TIMESTAMP_TOO_LATEST = 22103;</code>
     *
     * <pre>
     * getMinMessageIdByTime
     * </pre>
     */
    public static final int ERROR_BROKER_TIMESTAMP_TOO_LATEST_VALUE = 22103;
    /**
     * <code>ERROR_BROKER_MESSAGE_FORMAT_INVALID = 22104;</code>
     */
    public static final int ERROR_BROKER_MESSAGE_FORMAT_INVALID_VALUE = 22104;
    /**
     * <code>ERROR_BROKER_REPEATED_ADD_TOPIC_PARTITION = 22201;</code>
     *
     * <pre>
     * SYS ERROR X22XX
     * </pre>
     */
    public static final int ERROR_BROKER_REPEATED_ADD_TOPIC_PARTITION_VALUE = 22201;
    /**
     * <code>ERROR_BROKER_OPEN_FILE = 22202;</code>
     */
    public static final int ERROR_BROKER_OPEN_FILE_VALUE = 22202;
    /**
     * <code>ERROR_BROKER_WRITE_FILE = 22203;</code>
     */
    public static final int ERROR_BROKER_WRITE_FILE_VALUE = 22203;
    /**
     * <code>ERROR_BROKER_COMMIT_FILE = 22204;</code>
     */
    public static final int ERROR_BROKER_COMMIT_FILE_VALUE = 22204;
    /**
     * <code>ERROR_BROKER_CLOSE_FILE = 22205;</code>
     */
    public static final int ERROR_BROKER_CLOSE_FILE_VALUE = 22205;
    /**
     * <code>ERROR_BROKER_READ_FILE = 22206;</code>
     */
    public static final int ERROR_BROKER_READ_FILE_VALUE = 22206;
    /**
     * <code>ERROR_BROKER_FS_OPERATE = 22207;</code>
     */
    public static final int ERROR_BROKER_FS_OPERATE_VALUE = 22207;
    /**
     * <code>ERROR_BROKER_NO_DATA_IN_MEM = 22211;</code>
     */
    public static final int ERROR_BROKER_NO_DATA_IN_MEM_VALUE = 22211;
    /**
     * <code>ERROR_BROKER_RECOVER_FILE_MESSAGE_NO_MORE_MEMORY = 22212;</code>
     */
    public static final int ERROR_BROKER_RECOVER_FILE_MESSAGE_NO_MORE_MEMORY_VALUE = 22212;
    /**
     * <code>ERROR_BROKER_CREATE_THREAD = 32201;</code>
     */
    public static final int ERROR_BROKER_CREATE_THREAD_VALUE = 32201;
    /**
     * <code>ERROR_BROKER_MKDIR = 32202;</code>
     */
    public static final int ERROR_BROKER_MKDIR_VALUE = 32202;
    /**
     * <code>ERROR_BROKER_DATA_DIR_EMPTY = 32203;</code>
     */
    public static final int ERROR_BROKER_DATA_DIR_EMPTY_VALUE = 32203;
    /**
     * <code>ERROR_CLIENT_INIT_TWICE = 13201;</code>
     *
     * <pre>
     *&#47;////////////////////////////////
     *       CLIENT ERROR X3XXX
     * /////////////////////////////////
     * SYS ERROR X32XX
     * </pre>
     */
    public static final int ERROR_CLIENT_INIT_TWICE_VALUE = 13201;
    /**
     * <code>ERROR_CLIENT_INIT_INVALID_PARAMETERS = 13202;</code>
     */
    public static final int ERROR_CLIENT_INIT_INVALID_PARAMETERS_VALUE = 13202;
    /**
     * <code>ERROR_CLIENT_RPC_CONNECT = 13203;</code>
     */
    public static final int ERROR_CLIENT_RPC_CONNECT_VALUE = 13203;
    /**
     * <code>ERROR_CLIENT_GET_ADMIN_INFO_FAILED = 13204;</code>
     */
    public static final int ERROR_CLIENT_GET_ADMIN_INFO_FAILED_VALUE = 13204;
    /**
     * <code>ERROR_CLIENT_GET_BROKER_ADDRESS_FAILED = 13205;</code>
     */
    public static final int ERROR_CLIENT_GET_BROKER_ADDRESS_FAILED_VALUE = 13205;
    /**
     * <code>ERROR_CLIENT_INVALID_RESPONSE = 13206;</code>
     */
    public static final int ERROR_CLIENT_INVALID_RESPONSE_VALUE = 13206;
    /**
     * <code>ERROR_CLIENT_SYS_STOPPED = 13207;</code>
     */
    public static final int ERROR_CLIENT_SYS_STOPPED_VALUE = 13207;
    /**
     * <code>ERROR_CLIENT_ARPC_ERROR = 13208;</code>
     */
    public static final int ERROR_CLIENT_ARPC_ERROR_VALUE = 13208;
    /**
     * <code>ERROR_CLIENT_READ_MESSAGE_TIMEOUT = 13209;</code>
     */
    public static final int ERROR_CLIENT_READ_MESSAGE_TIMEOUT_VALUE = 13209;
    /**
     * <code>ERROR_CLIENT_SEND_BUFFER_FULL = 13210;</code>
     */
    public static final int ERROR_CLIENT_SEND_BUFFER_FULL_VALUE = 13210;
    /**
     * <code>ERROR_CLIENT_SOME_MESSAGE_SEND_FAILED = 13211;</code>
     */
    public static final int ERROR_CLIENT_SOME_MESSAGE_SEND_FAILED_VALUE = 13211;
    /**
     * <code>ERROR_CLIENT_INIT_FAILED = 13212;</code>
     */
    public static final int ERROR_CLIENT_INIT_FAILED_VALUE = 13212;
    /**
     * <code>ERROR_CLIENT_NO_MORE_MESSAGE = 13213;</code>
     */
    public static final int ERROR_CLIENT_NO_MORE_MESSAGE_VALUE = 13213;
    /**
     * <code>ERROR_CLIENT_INVALID_PARAMETERS = 13214;</code>
     */
    public static final int ERROR_CLIENT_INVALID_PARAMETERS_VALUE = 13214;
    /**
     * <code>ERROR_CLIENT_NOT_INITED = 13215;</code>
     */
    public static final int ERROR_CLIENT_NOT_INITED_VALUE = 13215;
    /**
     * <code>ERROR_CLIENT_INVALID_PARTITIONID = 13216;</code>
     */
    public static final int ERROR_CLIENT_INVALID_PARTITIONID_VALUE = 13216;
    /**
     * <code>ERROR_CLIENT_EOF = 13217;</code>
     */
    public static final int ERROR_CLIENT_EOF_VALUE = 13217;
    /**
     * <code>ERROR_CLIENT_EXCEED_TIME_STAMP_LIMIT = 13219;</code>
     */
    public static final int ERROR_CLIENT_EXCEED_TIME_STAMP_LIMIT_VALUE = 13219;


    public final int getNumber() { return value; }

    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 0: return ERROR_NONE;
        case 1: return ERROR_UNKNOWN;
        case 10000: return ERROR_INFO_START;
        case 20000: return ERROR_WARN_START;
        case 30000: return ERROR_FATAL_START;
        case 30002: return ERROR_WORKER_DEAD;
        case 3004: return ERROR_DECOMPRESS_MESSAGE;
        case 21101: return ERROR_ADMIN_TOPIC_HAS_EXISTED;
        case 21102: return ERROR_ADMIN_TOPIC_NOT_EXISTED;
        case 21103: return ERROR_ADMIN_INVALID_PARAMETER;
        case 21104: return ERROR_ADMIN_NOT_LEADER;
        case 21105: return ERROR_ADMIN_PARTITION_NOT_EXISTED;
        case 21106: return ERROR_ADMIN_UNKNOWN_COMMAND;
        case 21107: return ERROR_ADMIN_IP_SET_INVALID;
        case 21108: return ERROR_ADMIN_INVALID_CONFIG;
        case 21109: return ERROR_BROKER_IS_UPGRADING;
        case 21110: return ERROR_UPGRADE_BROKER_BEFORE_ADMIN;
        case 21111: return ERROR_WRITE_BROKER_TARGET_VERSION;
        case 21112: return ERROR_UPGRADE_VERSION_SAME_AS_CURRENT;
        case 21113: return ERROR_ADMIN_APPLICATION_ID_CHANGED;
        case 21114: return ERROR_CONFIG_IS_ROLLBACKING;
        case 21115: return ERROR_NOT_NEED_ROLLBACK;
        case 21116: return ERROR_WRITE_ROLLBACK_FILE;
        case 21117: return ERROR_UPGRADE_ROLE_VERSION;
        case 21201: return ERROR_ADMIN_NOT_ENOUGH_RESOURCE;
        case 21202: return ERROR_ADMIN_OPERATION_FAILED;
        case 21203: return ERROR_ADMIN_CLEAR_OLD_TOPIC_DATA_FAILED;
        case 31201: return ERROR_ADMIN_SYS_NOT_INIT;
        case 31202: return ERROR_ADMIN_NOT_IMPLEMENTED;
        case 12101: return ERROR_BROKER_FAIL;
        case 12102: return ERROR_BROKER_STOPPED;
        case 12103: return ERROR_BROKER_BUSY;
        case 12104: return ERROR_BROKER_TOPIC_PARTITION_NOT_FOUND;
        case 12105: return ERROR_BROKER_TOPIC_PARTITION_NOT_RUNNING;
        case 12106: return ERROR_BROKER_REQUEST_INVALID;
        case 12107: return ERROR_BROKER_NO_DATA;
        case 12108: return ERROR_BROKER_TOPIC_NOT_SUPPORT_FIELD_FILTER;
        case 12109: return ERROR_BROKER_INIT_FIELD_FILTER_FAILD;
        case 12110: return ERROR_BROKER_SESSION_CHANGED;
        case 22101: return ERROR_BROKER_SOME_MESSAGE_LOST;
        case 22102: return ERROR_BROKER_MSG_LENGTH_EXCEEDED;
        case 22103: return ERROR_BROKER_TIMESTAMP_TOO_LATEST;
        case 22104: return ERROR_BROKER_MESSAGE_FORMAT_INVALID;
        case 22201: return ERROR_BROKER_REPEATED_ADD_TOPIC_PARTITION;
        case 22202: return ERROR_BROKER_OPEN_FILE;
        case 22203: return ERROR_BROKER_WRITE_FILE;
        case 22204: return ERROR_BROKER_COMMIT_FILE;
        case 22205: return ERROR_BROKER_CLOSE_FILE;
        case 22206: return ERROR_BROKER_READ_FILE;
        case 22207: return ERROR_BROKER_FS_OPERATE;
        case 22211: return ERROR_BROKER_NO_DATA_IN_MEM;
        case 22212: return ERROR_BROKER_RECOVER_FILE_MESSAGE_NO_MORE_MEMORY;
        case 32201: return ERROR_BROKER_CREATE_THREAD;
        case 32202: return ERROR_BROKER_MKDIR;
        case 32203: return ERROR_BROKER_DATA_DIR_EMPTY;
        case 13201: return ERROR_CLIENT_INIT_TWICE;
        case 13202: return ERROR_CLIENT_INIT_INVALID_PARAMETERS;
        case 13203: return ERROR_CLIENT_RPC_CONNECT;
        case 13204: return ERROR_CLIENT_GET_ADMIN_INFO_FAILED;
        case 13205: return ERROR_CLIENT_GET_BROKER_ADDRESS_FAILED;
        case 13206: return ERROR_CLIENT_INVALID_RESPONSE;
        case 13207: return ERROR_CLIENT_SYS_STOPPED;
        case 13208: return ERROR_CLIENT_ARPC_ERROR;
        case 13209: return ERROR_CLIENT_READ_MESSAGE_TIMEOUT;
        case 13210: return ERROR_CLIENT_SEND_BUFFER_FULL;
        case 13211: return ERROR_CLIENT_SOME_MESSAGE_SEND_FAILED;
        case 13212: return ERROR_CLIENT_INIT_FAILED;
        case 13213: return ERROR_CLIENT_NO_MORE_MESSAGE;
        case 13214: return ERROR_CLIENT_INVALID_PARAMETERS;
        case 13215: return ERROR_CLIENT_NOT_INITED;
        case 13216: return ERROR_CLIENT_INVALID_PARTITIONID;
        case 13217: return ERROR_CLIENT_EOF;
        case 13219: return ERROR_CLIENT_EXCEED_TIME_STAMP_LIMIT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.alibaba.search.swift.protocol.ErrCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:swift.protocol.ErrorCode)
  }

  /**
   * Protobuf enum {@code swift.protocol.ErrorLevel}
   */
  public enum ErrorLevel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR_LEVEL_INFO = 0;</code>
     */
    ERROR_LEVEL_INFO(0, 0),
    /**
     * <code>ERROR_LEVEL_WARN = 1;</code>
     */
    ERROR_LEVEL_WARN(1, 1),
    /**
     * <code>ERROR_LEVEL_FATAL = 2;</code>
     */
    ERROR_LEVEL_FATAL(2, 2),
    ;

    /**
     * <code>ERROR_LEVEL_INFO = 0;</code>
     */
    public static final int ERROR_LEVEL_INFO_VALUE = 0;
    /**
     * <code>ERROR_LEVEL_WARN = 1;</code>
     */
    public static final int ERROR_LEVEL_WARN_VALUE = 1;
    /**
     * <code>ERROR_LEVEL_FATAL = 2;</code>
     */
    public static final int ERROR_LEVEL_FATAL_VALUE = 2;


    public final int getNumber() { return value; }

    public static ErrorLevel valueOf(int value) {
      switch (value) {
        case 0: return ERROR_LEVEL_INFO;
        case 1: return ERROR_LEVEL_WARN;
        case 2: return ERROR_LEVEL_FATAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorLevel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorLevel>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorLevel>() {
            public ErrorLevel findValueByNumber(int number) {
              return ErrorLevel.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.alibaba.search.swift.protocol.ErrCode.getDescriptor().getEnumTypes().get(1);
    }

    private static final ErrorLevel[] VALUES = values();

    public static ErrorLevel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorLevel(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:swift.protocol.ErrorLevel)
  }

  public interface ErrorInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];
    /**
     * <code>optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];</code>
     */
    com.alibaba.search.swift.protocol.ErrCode.ErrorCode getErrCode();

    // optional string errMsg = 2;
    /**
     * <code>optional string errMsg = 2;</code>
     */
    boolean hasErrMsg();
    /**
     * <code>optional string errMsg = 2;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string errMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code swift.protocol.ErrorInfo}
   */
  public static final class ErrorInfo extends
      com.google.protobuf.GeneratedMessage
      implements ErrorInfoOrBuilder {
    // Use ErrorInfo.newBuilder() to construct.
    private ErrorInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ErrorInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ErrorInfo defaultInstance;
    public static ErrorInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ErrorInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.alibaba.search.swift.protocol.ErrCode.ErrorCode value = com.alibaba.search.swift.protocol.ErrCode.ErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                errCode_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.search.swift.protocol.ErrCode.internal_static_swift_protocol_ErrorInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.search.swift.protocol.ErrCode.internal_static_swift_protocol_ErrorInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.search.swift.protocol.ErrCode.ErrorInfo.class, com.alibaba.search.swift.protocol.ErrCode.ErrorInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ErrorInfo> PARSER =
        new com.google.protobuf.AbstractParser<ErrorInfo>() {
      public ErrorInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private com.alibaba.search.swift.protocol.ErrCode.ErrorCode errCode_;
    /**
     * <code>optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];</code>
     */
    public com.alibaba.search.swift.protocol.ErrCode.ErrorCode getErrCode() {
      return errCode_;
    }

    // optional string errMsg = 2;
    public static final int ERRMSG_FIELD_NUMBER = 2;
    private java.lang.Object errMsg_;
    /**
     * <code>optional string errMsg = 2;</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string errMsg = 2;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errCode_ = com.alibaba.search.swift.protocol.ErrCode.ErrorCode.ERROR_NONE;
      errMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.search.swift.protocol.ErrCode.ErrorInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code swift.protocol.ErrorInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.alibaba.search.swift.protocol.ErrCode.ErrorInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.search.swift.protocol.ErrCode.internal_static_swift_protocol_ErrorInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.search.swift.protocol.ErrCode.internal_static_swift_protocol_ErrorInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.search.swift.protocol.ErrCode.ErrorInfo.class, com.alibaba.search.swift.protocol.ErrCode.ErrorInfo.Builder.class);
      }

      // Construct using com.alibaba.search.swift.protocol.ErrCode.ErrorInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errCode_ = com.alibaba.search.swift.protocol.ErrCode.ErrorCode.ERROR_NONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.search.swift.protocol.ErrCode.internal_static_swift_protocol_ErrorInfo_descriptor;
      }

      public com.alibaba.search.swift.protocol.ErrCode.ErrorInfo getDefaultInstanceForType() {
        return com.alibaba.search.swift.protocol.ErrCode.ErrorInfo.getDefaultInstance();
      }

      public com.alibaba.search.swift.protocol.ErrCode.ErrorInfo build() {
        com.alibaba.search.swift.protocol.ErrCode.ErrorInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.search.swift.protocol.ErrCode.ErrorInfo buildPartial() {
        com.alibaba.search.swift.protocol.ErrCode.ErrorInfo result = new com.alibaba.search.swift.protocol.ErrCode.ErrorInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMsg_ = errMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.search.swift.protocol.ErrCode.ErrorInfo) {
          return mergeFrom((com.alibaba.search.swift.protocol.ErrCode.ErrorInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.search.swift.protocol.ErrCode.ErrorInfo other) {
        if (other == com.alibaba.search.swift.protocol.ErrCode.ErrorInfo.getDefaultInstance()) return this;
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000002;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.search.swift.protocol.ErrCode.ErrorInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.search.swift.protocol.ErrCode.ErrorInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];
      private com.alibaba.search.swift.protocol.ErrCode.ErrorCode errCode_ = com.alibaba.search.swift.protocol.ErrCode.ErrorCode.ERROR_NONE;
      /**
       * <code>optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];</code>
       */
      public com.alibaba.search.swift.protocol.ErrCode.ErrorCode getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];</code>
       */
      public Builder setErrCode(com.alibaba.search.swift.protocol.ErrCode.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .swift.protocol.ErrorCode errCode = 1 [default = ERROR_NONE];</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = com.alibaba.search.swift.protocol.ErrCode.ErrorCode.ERROR_NONE;
        onChanged();
        return this;
      }

      // optional string errMsg = 2;
      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:swift.protocol.ErrorInfo)
    }

    static {
      defaultInstance = new ErrorInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:swift.protocol.ErrorInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_swift_protocol_ErrorInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_swift_protocol_ErrorInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034swift/protocol/ErrCode.proto\022\016swift.pr" +
      "otocol\"S\n\tErrorInfo\0226\n\007errCode\030\001 \001(\0162\031.s" +
      "wift.protocol.ErrorCode:\nERROR_NONE\022\016\n\006e" +
      "rrMsg\030\002 \001(\t*\210\024\n\tErrorCode\022\016\n\nERROR_NONE\020" +
      "\000\022\021\n\rERROR_UNKNOWN\020\001\022\025\n\020ERROR_INFO_START" +
      "\020\220N\022\026\n\020ERROR_WARN_START\020\240\234\001\022\027\n\021ERROR_FAT" +
      "AL_START\020\260\352\001\022\027\n\021ERROR_WORKER_DEAD\020\262\352\001\022\035\n" +
      "\030ERROR_DECOMPRESS_MESSAGE\020\274\027\022#\n\035ERROR_AD" +
      "MIN_TOPIC_HAS_EXISTED\020\355\244\001\022#\n\035ERROR_ADMIN" +
      "_TOPIC_NOT_EXISTED\020\356\244\001\022#\n\035ERROR_ADMIN_IN",
      "VALID_PARAMETER\020\357\244\001\022\034\n\026ERROR_ADMIN_NOT_L" +
      "EADER\020\360\244\001\022\'\n!ERROR_ADMIN_PARTITION_NOT_E" +
      "XISTED\020\361\244\001\022!\n\033ERROR_ADMIN_UNKNOWN_COMMAN" +
      "D\020\362\244\001\022 \n\032ERROR_ADMIN_IP_SET_INVALID\020\363\244\001\022" +
      " \n\032ERROR_ADMIN_INVALID_CONFIG\020\364\244\001\022\037\n\031ERR" +
      "OR_BROKER_IS_UPGRADING\020\365\244\001\022\'\n!ERROR_UPGR" +
      "ADE_BROKER_BEFORE_ADMIN\020\366\244\001\022\'\n!ERROR_WRI" +
      "TE_BROKER_TARGET_VERSION\020\367\244\001\022+\n%ERROR_UP" +
      "GRADE_VERSION_SAME_AS_CURRENT\020\370\244\001\022(\n\"ERR" +
      "OR_ADMIN_APPLICATION_ID_CHANGED\020\371\244\001\022!\n\033E",
      "RROR_CONFIG_IS_ROLLBACKING\020\372\244\001\022\035\n\027ERROR_" +
      "NOT_NEED_ROLLBACK\020\373\244\001\022\037\n\031ERROR_WRITE_ROL" +
      "LBACK_FILE\020\374\244\001\022 \n\032ERROR_UPGRADE_ROLE_VER" +
      "SION\020\375\244\001\022%\n\037ERROR_ADMIN_NOT_ENOUGH_RESOU" +
      "RCE\020\321\245\001\022\"\n\034ERROR_ADMIN_OPERATION_FAILED\020" +
      "\322\245\001\022-\n\'ERROR_ADMIN_CLEAR_OLD_TOPIC_DATA_" +
      "FAILED\020\323\245\001\022\036\n\030ERROR_ADMIN_SYS_NOT_INIT\020\341" +
      "\363\001\022!\n\033ERROR_ADMIN_NOT_IMPLEMENTED\020\342\363\001\022\026\n" +
      "\021ERROR_BROKER_FAIL\020\305^\022\031\n\024ERROR_BROKER_ST" +
      "OPPED\020\306^\022\026\n\021ERROR_BROKER_BUSY\020\307^\022+\n&ERRO",
      "R_BROKER_TOPIC_PARTITION_NOT_FOUND\020\310^\022-\n" +
      "(ERROR_BROKER_TOPIC_PARTITION_NOT_RUNNIN" +
      "G\020\311^\022!\n\034ERROR_BROKER_REQUEST_INVALID\020\312^\022" +
      "\031\n\024ERROR_BROKER_NO_DATA\020\313^\0220\n+ERROR_BROK" +
      "ER_TOPIC_NOT_SUPPORT_FIELD_FILTER\020\314^\022)\n$" +
      "ERROR_BROKER_INIT_FIELD_FILTER_FAILD\020\315^\022" +
      "!\n\034ERROR_BROKER_SESSION_CHANGED\020\316^\022$\n\036ER" +
      "ROR_BROKER_SOME_MESSAGE_LOST\020\325\254\001\022&\n ERRO" +
      "R_BROKER_MSG_LENGTH_EXCEEDED\020\326\254\001\022\'\n!ERRO" +
      "R_BROKER_TIMESTAMP_TOO_LATEST\020\327\254\001\022)\n#ERR",
      "OR_BROKER_MESSAGE_FORMAT_INVALID\020\330\254\001\022/\n)" +
      "ERROR_BROKER_REPEATED_ADD_TOPIC_PARTITIO" +
      "N\020\271\255\001\022\034\n\026ERROR_BROKER_OPEN_FILE\020\272\255\001\022\035\n\027E" +
      "RROR_BROKER_WRITE_FILE\020\273\255\001\022\036\n\030ERROR_BROK" +
      "ER_COMMIT_FILE\020\274\255\001\022\035\n\027ERROR_BROKER_CLOSE" +
      "_FILE\020\275\255\001\022\034\n\026ERROR_BROKER_READ_FILE\020\276\255\001\022" +
      "\035\n\027ERROR_BROKER_FS_OPERATE\020\277\255\001\022!\n\033ERROR_" +
      "BROKER_NO_DATA_IN_MEM\020\303\255\001\0226\n0ERROR_BROKE" +
      "R_RECOVER_FILE_MESSAGE_NO_MORE_MEMORY\020\304\255" +
      "\001\022 \n\032ERROR_BROKER_CREATE_THREAD\020\311\373\001\022\030\n\022E",
      "RROR_BROKER_MKDIR\020\312\373\001\022!\n\033ERROR_BROKER_DA" +
      "TA_DIR_EMPTY\020\313\373\001\022\034\n\027ERROR_CLIENT_INIT_TW" +
      "ICE\020\221g\022)\n$ERROR_CLIENT_INIT_INVALID_PARA" +
      "METERS\020\222g\022\035\n\030ERROR_CLIENT_RPC_CONNECT\020\223g" +
      "\022\'\n\"ERROR_CLIENT_GET_ADMIN_INFO_FAILED\020\224" +
      "g\022+\n&ERROR_CLIENT_GET_BROKER_ADDRESS_FAI" +
      "LED\020\225g\022\"\n\035ERROR_CLIENT_INVALID_RESPONSE\020" +
      "\226g\022\035\n\030ERROR_CLIENT_SYS_STOPPED\020\227g\022\034\n\027ERR" +
      "OR_CLIENT_ARPC_ERROR\020\230g\022&\n!ERROR_CLIENT_" +
      "READ_MESSAGE_TIMEOUT\020\231g\022\"\n\035ERROR_CLIENT_",
      "SEND_BUFFER_FULL\020\232g\022*\n%ERROR_CLIENT_SOME" +
      "_MESSAGE_SEND_FAILED\020\233g\022\035\n\030ERROR_CLIENT_" +
      "INIT_FAILED\020\234g\022!\n\034ERROR_CLIENT_NO_MORE_M" +
      "ESSAGE\020\235g\022$\n\037ERROR_CLIENT_INVALID_PARAME" +
      "TERS\020\236g\022\034\n\027ERROR_CLIENT_NOT_INITED\020\237g\022%\n" +
      " ERROR_CLIENT_INVALID_PARTITIONID\020\240g\022\025\n\020" +
      "ERROR_CLIENT_EOF\020\241g\022)\n$ERROR_CLIENT_EXCE" +
      "ED_TIME_STAMP_LIMIT\020\243g*O\n\nErrorLevel\022\024\n\020" +
      "ERROR_LEVEL_INFO\020\000\022\024\n\020ERROR_LEVEL_WARN\020\001" +
      "\022\025\n\021ERROR_LEVEL_FATAL\020\002B#\n!com.alibaba.s",
      "earch.swift.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_swift_protocol_ErrorInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_swift_protocol_ErrorInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_swift_protocol_ErrorInfo_descriptor,
              new java.lang.String[] { "ErrCode", "ErrMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
