# -*- mode: python -*-

Import('env')
env = env.Clone()

document_rewriter_source=Glob('*.cpp')

#env.aLibrary(target='indexlib_document_rewriter', source=document_rewriter_source)

env.aDirs('test')
Return(['document_rewriter_source'] )
