# -*- mode: python -*-
import platform
Import('env')
env = env.Clone();

numeric_compress_ut_libs = [
    'indexlib_basic',
    'fslib-framework',
    'autil',
    'gmock',
    'gtest',
    'pthread'
]

numeric_compress_case_cpps=Glob('*_unittest.cpp')
numeric_compress_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    numeric_compress_case_cpps,
]

env.aTest(target = 'ie_numeric_compress_unittest',
          source = numeric_compress_ut_test_sources,
          LIBS= numeric_compress_ut_libs)

