# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

testlib_qrs_sources = Glob('*.cpp')

testlib_qrs = env.aStaticLibrary(target = 'testlib_qrs', source = testlib_qrs_sources)

#env.aDirs('test')

Return(['testlib_qrs_sources'])
