# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

sample_udaf_plugin = env.aLibrary(
    target='TestSqlAggFuncPlugin',
    source = Glob('*.cpp'),
    LIBS = ['ha3_sql'],
)

Return(['sample_udaf_plugin'])
