# -*- mode: python -*-

Import('env')

env = env.Clone()

pb_SqlSearch = env.aCompileProto('SqlSearch.proto')

proto_sources = (pb_SqlSearch)

env.aLibrary(
    target='ha3_suez_turing_sql_proto',
    source=proto_sources)

Return(['proto_sources'])
