# -*- mode: python -*-

Import('env')
env = env.Clone()

document_kvparser_ut_libs = [
    'indexlib_testlib',
    'indexlib_indextest_common',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_common',
    'indexlib_document',
    'indexlib_plugin',
    'indexlib_configtest',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
]

document_kvparser_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
]

env.aTest(target = 'indexlib_document_kvparser_unittest',
          source = document_kvparser_ut_test_sources,
          LIBS = document_kvparser_ut_libs)
