# -*- mode: python -*-
import platform
Import('env')
env = env.Clone();

mem_control_ut_libs = [
    'indexlib_basic',
    'fslib-framework',
    'autil',
    'gmock',
    'gtest',
    'pthread'
]

mem_control_case_cpps=Glob('*_unittest.cpp')
mem_control_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    mem_control_case_cpps,
]

env.aTest(target = 'ie_mem_control_unittest',
          source = mem_control_ut_test_sources,
          LIBS= mem_control_ut_libs)

