# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

testlib_summary_sources = Glob('*.cpp')

testlib_summary = env.aStaticLibrary(target = 'testlib_summary', source = testlib_summary_sources)

#env.aDirs('test')

Return(['testlib_summary_sources'])
