load('//aios/storage:defs.bzl', 'strict_cc_fast_test')
strict_cc_fast_test(
    name='DataStatisticsMetaTest',
    srcs=['DataStatisticsMetaTest.cpp'],
    copts=['-fno-access-control'],
    deps=[
        '//aios/storage/indexlib/index/field_meta/meta:DataStatisticsMeta',
        '//aios/unittest_framework'
    ]
)
