#include "navi/example/TestResource.h"
#include "navi/engine/Data.h"
#include "navi/engine/ResourceCreator.h"
#include "navi/log/NaviLogger.h"

namespace navi {

REGISTER_RESOURCE(TestStaticGraphLoaderR);
REGISTER_RESOURCE(TestAsyncPipeCreateR);

REGISTER_RESOURCE(A);
REGISTER_RESOURCE(B);
REGISTER_RESOURCE(C);
REGISTER_RESOURCE(D);
REGISTER_RESOURCE(ER);
REGISTER_RESOURCE(F);
REGISTER_RESOURCE(G);
REGISTER_RESOURCE(H);
REGISTER_RESOURCE(K);
REGISTER_RESOURCE(M);
REGISTER_RESOURCE(NR);
REGISTER_RESOURCE(U);
REGISTER_RESOURCE(V);
REGISTER_RESOURCE(W);
REGISTER_RESOURCE(X);
REGISTER_RESOURCE(DependOnBizResource);
REGISTER_RESOURCE(ProduceTest);
REGISTER_RESOURCE(External);
REGISTER_RESOURCE(KernelTestR1);
REGISTER_RESOURCE(KernelTestR2);
REGISTER_RESOURCE(KernelTestR3);
REGISTER_RESOURCE(KernelTestR4);
REGISTER_RESOURCE(KernelTestBuildR);
REGISTER_RESOURCE(KernelTestRFailed);
REGISTER_RESOURCE(KernelTestR5);
REGISTER_RESOURCE(ReplaceA);
REGISTER_RESOURCE(ReplaceAA);
REGISTER_RESOURCE(ReplaceB);

const std::string TestSnapshotR::RESOURCE_ID = "navi.test.test_snapshot_r";

REGISTER_RESOURCE(TestSnapshotR);

}

