#include "navi/example/TestResource.h"

namespace navi {

DECLARE_RESOURCE(TEST_BIZ_RESOURCE, RS_BIZ_PART, "");
REGISTER_RESOURCE(TEST_BIZ_RESOURCE);

DECLARE_RESOURCE(TEST_BIZ_RESOURCE_RUN_GRAPH, RS_SUB_GRAPH, "");
REGISTER_RESOURCE(TEST_BIZ_RESOURCE_RUN_GRAPH);

}

