# -*- mode: python -*-

Import('env')

env = env.Clone()

partition_split_merger_sources = [
    'main.cpp',
    'PartitionSplitMerger.cpp',
    'PartitionSplitChecker.cpp',
]  + env['build_signature_src']

env.aLibrary(target = 'partition_split_merger',
             source = partition_split_merger_sources)

libsname = ['build_service', 'indexlib', 'hiredis'] + env['bs_worker_lib']

env.aProgramAndInstall(target = 'bs_partition_split_merger',
                       source = partition_split_merger_sources,
                       LIBS = libsname,
                       LIBATTRS = { 'partition_split_merger' : 'static'});

env.aDirs('test')
