# -*- mode: python -*-

Import('env')
env = env.Clone()

range_test_sources = [
    '#indexlib/test/dotest.cpp',
    'range_index_reader_unittest.cpp',
]

date_libs = [
    'indexlib_indextest_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
    'pthread'
]

env.aTest(target = 'ie_range_unittest', 
          source = range_test_sources, LIBS = date_libs)


