# -*- mode: python -*-
import platform
Import('env')
env = env.Clone();

document_deduper_ut_libs = [
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'fslib-framework',
    'autil',
    'gmock',
    'gtest',
    'pthread'
]

document_deduper_case_cpps=Glob('*_unittest.cpp')
document_deduper_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    document_deduper_case_cpps,
]

env.aTest(target = 'ie_document_deduper_unittest',
          source = document_deduper_ut_test_sources,
          LIBS= document_deduper_ut_libs)

