node {
  name: "ha3_request"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_VARIANT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        unknown_rank: true
      }
    }
  }
}
node {
  name: "init_request"
  op: "RequestInitOp"
  input: "ha3_request"
}
node {
  name: "create_range"
  op: "LayerMetasCreateOp"
  input: "init_request"
}
node {
  name: "split_range"
  op: "RangeSplitOp"
  input: "create_range"
  attr {
    key: "N"
    value {
      i: 32
    }
  }
}
node {
  name: "resource_prepare"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare"
  op: "SeekIteratorPrepareOp"
  input: "split_range"
  input: "resource_prepare"
}
node {
  name: "agg_prepare"
  op: "AggPrepareOp"
  input: "resource_prepare"
  input: "^seek_prepare"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg"
  op: "SeekAndAggOp"
  input: "agg_prepare"
  input: "seek_prepare"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_1"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_1"
  op: "SeekIteratorPrepareOp"
  input: "split_range:1"
  input: "resource_prepare_1"
}
node {
  name: "agg_prepare_1"
  op: "AggPrepareOp"
  input: "resource_prepare_1"
  input: "^seek_prepare_1"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_1"
  op: "SeekAndAggOp"
  input: "agg_prepare_1"
  input: "seek_prepare_1"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_2"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_2"
  op: "SeekIteratorPrepareOp"
  input: "split_range:2"
  input: "resource_prepare_2"
}
node {
  name: "agg_prepare_2"
  op: "AggPrepareOp"
  input: "resource_prepare_2"
  input: "^seek_prepare_2"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_2"
  op: "SeekAndAggOp"
  input: "agg_prepare_2"
  input: "seek_prepare_2"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_3"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_3"
  op: "SeekIteratorPrepareOp"
  input: "split_range:3"
  input: "resource_prepare_3"
}
node {
  name: "agg_prepare_3"
  op: "AggPrepareOp"
  input: "resource_prepare_3"
  input: "^seek_prepare_3"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_3"
  op: "SeekAndAggOp"
  input: "agg_prepare_3"
  input: "seek_prepare_3"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_4"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_4"
  op: "SeekIteratorPrepareOp"
  input: "split_range:4"
  input: "resource_prepare_4"
}
node {
  name: "agg_prepare_4"
  op: "AggPrepareOp"
  input: "resource_prepare_4"
  input: "^seek_prepare_4"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_4"
  op: "SeekAndAggOp"
  input: "agg_prepare_4"
  input: "seek_prepare_4"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_5"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_5"
  op: "SeekIteratorPrepareOp"
  input: "split_range:5"
  input: "resource_prepare_5"
}
node {
  name: "agg_prepare_5"
  op: "AggPrepareOp"
  input: "resource_prepare_5"
  input: "^seek_prepare_5"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_5"
  op: "SeekAndAggOp"
  input: "agg_prepare_5"
  input: "seek_prepare_5"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_6"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_6"
  op: "SeekIteratorPrepareOp"
  input: "split_range:6"
  input: "resource_prepare_6"
}
node {
  name: "agg_prepare_6"
  op: "AggPrepareOp"
  input: "resource_prepare_6"
  input: "^seek_prepare_6"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_6"
  op: "SeekAndAggOp"
  input: "agg_prepare_6"
  input: "seek_prepare_6"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_7"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_7"
  op: "SeekIteratorPrepareOp"
  input: "split_range:7"
  input: "resource_prepare_7"
}
node {
  name: "agg_prepare_7"
  op: "AggPrepareOp"
  input: "resource_prepare_7"
  input: "^seek_prepare_7"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_7"
  op: "SeekAndAggOp"
  input: "agg_prepare_7"
  input: "seek_prepare_7"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_8"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_8"
  op: "SeekIteratorPrepareOp"
  input: "split_range:8"
  input: "resource_prepare_8"
}
node {
  name: "agg_prepare_8"
  op: "AggPrepareOp"
  input: "resource_prepare_8"
  input: "^seek_prepare_8"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_8"
  op: "SeekAndAggOp"
  input: "agg_prepare_8"
  input: "seek_prepare_8"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_9"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_9"
  op: "SeekIteratorPrepareOp"
  input: "split_range:9"
  input: "resource_prepare_9"
}
node {
  name: "agg_prepare_9"
  op: "AggPrepareOp"
  input: "resource_prepare_9"
  input: "^seek_prepare_9"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_9"
  op: "SeekAndAggOp"
  input: "agg_prepare_9"
  input: "seek_prepare_9"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_10"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_10"
  op: "SeekIteratorPrepareOp"
  input: "split_range:10"
  input: "resource_prepare_10"
}
node {
  name: "agg_prepare_10"
  op: "AggPrepareOp"
  input: "resource_prepare_10"
  input: "^seek_prepare_10"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_10"
  op: "SeekAndAggOp"
  input: "agg_prepare_10"
  input: "seek_prepare_10"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_11"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_11"
  op: "SeekIteratorPrepareOp"
  input: "split_range:11"
  input: "resource_prepare_11"
}
node {
  name: "agg_prepare_11"
  op: "AggPrepareOp"
  input: "resource_prepare_11"
  input: "^seek_prepare_11"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_11"
  op: "SeekAndAggOp"
  input: "agg_prepare_11"
  input: "seek_prepare_11"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_12"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_12"
  op: "SeekIteratorPrepareOp"
  input: "split_range:12"
  input: "resource_prepare_12"
}
node {
  name: "agg_prepare_12"
  op: "AggPrepareOp"
  input: "resource_prepare_12"
  input: "^seek_prepare_12"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_12"
  op: "SeekAndAggOp"
  input: "agg_prepare_12"
  input: "seek_prepare_12"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_13"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_13"
  op: "SeekIteratorPrepareOp"
  input: "split_range:13"
  input: "resource_prepare_13"
}
node {
  name: "agg_prepare_13"
  op: "AggPrepareOp"
  input: "resource_prepare_13"
  input: "^seek_prepare_13"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_13"
  op: "SeekAndAggOp"
  input: "agg_prepare_13"
  input: "seek_prepare_13"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_14"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_14"
  op: "SeekIteratorPrepareOp"
  input: "split_range:14"
  input: "resource_prepare_14"
}
node {
  name: "agg_prepare_14"
  op: "AggPrepareOp"
  input: "resource_prepare_14"
  input: "^seek_prepare_14"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_14"
  op: "SeekAndAggOp"
  input: "agg_prepare_14"
  input: "seek_prepare_14"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_15"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_15"
  op: "SeekIteratorPrepareOp"
  input: "split_range:15"
  input: "resource_prepare_15"
}
node {
  name: "agg_prepare_15"
  op: "AggPrepareOp"
  input: "resource_prepare_15"
  input: "^seek_prepare_15"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_15"
  op: "SeekAndAggOp"
  input: "agg_prepare_15"
  input: "seek_prepare_15"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_16"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_16"
  op: "SeekIteratorPrepareOp"
  input: "split_range:16"
  input: "resource_prepare_16"
}
node {
  name: "agg_prepare_16"
  op: "AggPrepareOp"
  input: "resource_prepare_16"
  input: "^seek_prepare_16"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_16"
  op: "SeekAndAggOp"
  input: "agg_prepare_16"
  input: "seek_prepare_16"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_17"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_17"
  op: "SeekIteratorPrepareOp"
  input: "split_range:17"
  input: "resource_prepare_17"
}
node {
  name: "agg_prepare_17"
  op: "AggPrepareOp"
  input: "resource_prepare_17"
  input: "^seek_prepare_17"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_17"
  op: "SeekAndAggOp"
  input: "agg_prepare_17"
  input: "seek_prepare_17"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_18"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_18"
  op: "SeekIteratorPrepareOp"
  input: "split_range:18"
  input: "resource_prepare_18"
}
node {
  name: "agg_prepare_18"
  op: "AggPrepareOp"
  input: "resource_prepare_18"
  input: "^seek_prepare_18"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_18"
  op: "SeekAndAggOp"
  input: "agg_prepare_18"
  input: "seek_prepare_18"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_19"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_19"
  op: "SeekIteratorPrepareOp"
  input: "split_range:19"
  input: "resource_prepare_19"
}
node {
  name: "agg_prepare_19"
  op: "AggPrepareOp"
  input: "resource_prepare_19"
  input: "^seek_prepare_19"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_19"
  op: "SeekAndAggOp"
  input: "agg_prepare_19"
  input: "seek_prepare_19"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_20"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_20"
  op: "SeekIteratorPrepareOp"
  input: "split_range:20"
  input: "resource_prepare_20"
}
node {
  name: "agg_prepare_20"
  op: "AggPrepareOp"
  input: "resource_prepare_20"
  input: "^seek_prepare_20"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_20"
  op: "SeekAndAggOp"
  input: "agg_prepare_20"
  input: "seek_prepare_20"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_21"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_21"
  op: "SeekIteratorPrepareOp"
  input: "split_range:21"
  input: "resource_prepare_21"
}
node {
  name: "agg_prepare_21"
  op: "AggPrepareOp"
  input: "resource_prepare_21"
  input: "^seek_prepare_21"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_21"
  op: "SeekAndAggOp"
  input: "agg_prepare_21"
  input: "seek_prepare_21"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_22"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_22"
  op: "SeekIteratorPrepareOp"
  input: "split_range:22"
  input: "resource_prepare_22"
}
node {
  name: "agg_prepare_22"
  op: "AggPrepareOp"
  input: "resource_prepare_22"
  input: "^seek_prepare_22"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_22"
  op: "SeekAndAggOp"
  input: "agg_prepare_22"
  input: "seek_prepare_22"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_23"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_23"
  op: "SeekIteratorPrepareOp"
  input: "split_range:23"
  input: "resource_prepare_23"
}
node {
  name: "agg_prepare_23"
  op: "AggPrepareOp"
  input: "resource_prepare_23"
  input: "^seek_prepare_23"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_23"
  op: "SeekAndAggOp"
  input: "agg_prepare_23"
  input: "seek_prepare_23"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_24"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_24"
  op: "SeekIteratorPrepareOp"
  input: "split_range:24"
  input: "resource_prepare_24"
}
node {
  name: "agg_prepare_24"
  op: "AggPrepareOp"
  input: "resource_prepare_24"
  input: "^seek_prepare_24"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_24"
  op: "SeekAndAggOp"
  input: "agg_prepare_24"
  input: "seek_prepare_24"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_25"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_25"
  op: "SeekIteratorPrepareOp"
  input: "split_range:25"
  input: "resource_prepare_25"
}
node {
  name: "agg_prepare_25"
  op: "AggPrepareOp"
  input: "resource_prepare_25"
  input: "^seek_prepare_25"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_25"
  op: "SeekAndAggOp"
  input: "agg_prepare_25"
  input: "seek_prepare_25"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_26"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_26"
  op: "SeekIteratorPrepareOp"
  input: "split_range:26"
  input: "resource_prepare_26"
}
node {
  name: "agg_prepare_26"
  op: "AggPrepareOp"
  input: "resource_prepare_26"
  input: "^seek_prepare_26"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_26"
  op: "SeekAndAggOp"
  input: "agg_prepare_26"
  input: "seek_prepare_26"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_27"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_27"
  op: "SeekIteratorPrepareOp"
  input: "split_range:27"
  input: "resource_prepare_27"
}
node {
  name: "agg_prepare_27"
  op: "AggPrepareOp"
  input: "resource_prepare_27"
  input: "^seek_prepare_27"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_27"
  op: "SeekAndAggOp"
  input: "agg_prepare_27"
  input: "seek_prepare_27"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_28"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_28"
  op: "SeekIteratorPrepareOp"
  input: "split_range:28"
  input: "resource_prepare_28"
}
node {
  name: "agg_prepare_28"
  op: "AggPrepareOp"
  input: "resource_prepare_28"
  input: "^seek_prepare_28"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_28"
  op: "SeekAndAggOp"
  input: "agg_prepare_28"
  input: "seek_prepare_28"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_29"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_29"
  op: "SeekIteratorPrepareOp"
  input: "split_range:29"
  input: "resource_prepare_29"
}
node {
  name: "agg_prepare_29"
  op: "AggPrepareOp"
  input: "resource_prepare_29"
  input: "^seek_prepare_29"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_29"
  op: "SeekAndAggOp"
  input: "agg_prepare_29"
  input: "seek_prepare_29"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_30"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_30"
  op: "SeekIteratorPrepareOp"
  input: "split_range:30"
  input: "resource_prepare_30"
}
node {
  name: "agg_prepare_30"
  op: "AggPrepareOp"
  input: "resource_prepare_30"
  input: "^seek_prepare_30"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_30"
  op: "SeekAndAggOp"
  input: "agg_prepare_30"
  input: "seek_prepare_30"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_31"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_31"
  op: "SeekIteratorPrepareOp"
  input: "split_range:31"
  input: "resource_prepare_31"
}
node {
  name: "agg_prepare_31"
  op: "AggPrepareOp"
  input: "resource_prepare_31"
  input: "^seek_prepare_31"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_31"
  op: "SeekAndAggOp"
  input: "agg_prepare_31"
  input: "seek_prepare_31"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "AggMergeOp"
  op: "AggMergeOp"
  input: "seek_and_agg"
  input: "seek_and_agg_1"
  input: "seek_and_agg_2"
  input: "seek_and_agg_3"
  input: "seek_and_agg_4"
  input: "seek_and_agg_5"
  input: "seek_and_agg_6"
  input: "seek_and_agg_7"
  input: "seek_and_agg_8"
  input: "seek_and_agg_9"
  input: "seek_and_agg_10"
  input: "seek_and_agg_11"
  input: "seek_and_agg_12"
  input: "seek_and_agg_13"
  input: "seek_and_agg_14"
  input: "seek_and_agg_15"
  input: "seek_and_agg_16"
  input: "seek_and_agg_17"
  input: "seek_and_agg_18"
  input: "seek_and_agg_19"
  input: "seek_and_agg_20"
  input: "seek_and_agg_21"
  input: "seek_and_agg_22"
  input: "seek_and_agg_23"
  input: "seek_and_agg_24"
  input: "seek_and_agg_25"
  input: "seek_and_agg_26"
  input: "seek_and_agg_27"
  input: "seek_and_agg_28"
  input: "seek_and_agg_29"
  input: "seek_and_agg_30"
  input: "seek_and_agg_31"
  attr {
    key: "N"
    value {
      i: 32
    }
  }
}
node {
  name: "ha3_result"
  op: "AggResultConstructOp"
  input: "AggMergeOp"
}
node {
  name: "ha3_search_done"
  op: "NoOp"
  input: "^ha3_result"
}
versions {
  producer: 24
}
