node {
  name: "ha3_request"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_VARIANT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        unknown_rank: true
      }
    }
  }
}
node {
  name: "init_request"
  op: "RequestInitOp"
  input: "ha3_request"
}
node {
  name: "create_range"
  op: "LayerMetasCreateOp"
  input: "init_request"
}
node {
  name: "split_range"
  op: "RangeSplitOp"
  input: "create_range"
  attr {
    key: "N"
    value {
      i: 8
    }
  }
}
node {
  name: "resource_prepare"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare"
  op: "SeekIteratorPrepareOp"
  input: "split_range"
  input: "resource_prepare"
}
node {
  name: "agg_prepare"
  op: "AggPrepareOp"
  input: "resource_prepare"
  input: "^seek_prepare"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg"
  op: "SeekAndAggOp"
  input: "agg_prepare"
  input: "seek_prepare"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_1"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_1"
  op: "SeekIteratorPrepareOp"
  input: "split_range:1"
  input: "resource_prepare_1"
}
node {
  name: "agg_prepare_1"
  op: "AggPrepareOp"
  input: "resource_prepare_1"
  input: "^seek_prepare_1"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_1"
  op: "SeekAndAggOp"
  input: "agg_prepare_1"
  input: "seek_prepare_1"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_2"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_2"
  op: "SeekIteratorPrepareOp"
  input: "split_range:2"
  input: "resource_prepare_2"
}
node {
  name: "agg_prepare_2"
  op: "AggPrepareOp"
  input: "resource_prepare_2"
  input: "^seek_prepare_2"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_2"
  op: "SeekAndAggOp"
  input: "agg_prepare_2"
  input: "seek_prepare_2"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_3"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_3"
  op: "SeekIteratorPrepareOp"
  input: "split_range:3"
  input: "resource_prepare_3"
}
node {
  name: "agg_prepare_3"
  op: "AggPrepareOp"
  input: "resource_prepare_3"
  input: "^seek_prepare_3"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_3"
  op: "SeekAndAggOp"
  input: "agg_prepare_3"
  input: "seek_prepare_3"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_4"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_4"
  op: "SeekIteratorPrepareOp"
  input: "split_range:4"
  input: "resource_prepare_4"
}
node {
  name: "agg_prepare_4"
  op: "AggPrepareOp"
  input: "resource_prepare_4"
  input: "^seek_prepare_4"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_4"
  op: "SeekAndAggOp"
  input: "agg_prepare_4"
  input: "seek_prepare_4"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_5"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_5"
  op: "SeekIteratorPrepareOp"
  input: "split_range:5"
  input: "resource_prepare_5"
}
node {
  name: "agg_prepare_5"
  op: "AggPrepareOp"
  input: "resource_prepare_5"
  input: "^seek_prepare_5"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_5"
  op: "SeekAndAggOp"
  input: "agg_prepare_5"
  input: "seek_prepare_5"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_6"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_6"
  op: "SeekIteratorPrepareOp"
  input: "split_range:6"
  input: "resource_prepare_6"
}
node {
  name: "agg_prepare_6"
  op: "AggPrepareOp"
  input: "resource_prepare_6"
  input: "^seek_prepare_6"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_6"
  op: "SeekAndAggOp"
  input: "agg_prepare_6"
  input: "seek_prepare_6"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "resource_prepare_7"
  op: "PrepareExpressionResourceOp"
  input: "init_request"
}
node {
  name: "seek_prepare_7"
  op: "SeekIteratorPrepareOp"
  input: "split_range:7"
  input: "resource_prepare_7"
}
node {
  name: "agg_prepare_7"
  op: "AggPrepareOp"
  input: "resource_prepare_7"
  input: "^seek_prepare_7"
  attr {
    key: "json_path"
    value {
      s: ""
    }
  }
  attr {
    key: "relative_path"
    value {
      s: ""
    }
  }
}
node {
  name: "seek_and_agg_7"
  op: "SeekAndAggOp"
  input: "agg_prepare_7"
  input: "seek_prepare_7"
  attr {
    key: "batch_size"
    value {
      i: 1024
    }
  }
}
node {
  name: "AggMergeOp"
  op: "AggMergeOp"
  input: "seek_and_agg"
  input: "seek_and_agg_1"
  input: "seek_and_agg_2"
  input: "seek_and_agg_3"
  input: "seek_and_agg_4"
  input: "seek_and_agg_5"
  input: "seek_and_agg_6"
  input: "seek_and_agg_7"
  attr {
    key: "N"
    value {
      i: 8
    }
  }
}
node {
  name: "ha3_result"
  op: "AggResultConstructOp"
  input: "AggMergeOp"
}
node {
  name: "ha3_search_done"
  op: "NoOp"
  input: "^ha3_result"
}
versions {
  producer: 24
}
