/*
 * Copyright 2014-present Alibaba Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#pragma once

#include "autil/Log.h"
#include "autil/NoCopyable.h"
#include "indexlib/framework/index_task/IndexOperationDescription.h"
#include "indexlib/framework/index_task/IndexTaskContext.h"
#include "indexlib/index/common/patch/PatchFileInfos.h"

namespace indexlibv2::index {
class SrcDestPatchFileFinder;
}
namespace indexlibv2::framework {
class Segment;
}
namespace indexlibv2::config {
class IIndexConfig;
}
namespace indexlib::file_system {
class IDirectory;
}

namespace indexlibv2::table {

// 对 index/common/SrcDestPatchFileFinder 的封装，用来加载OpLog2PatchOperation生成在独立目录的patch文件
class PatchFileFinderUtil : private autil::NoCopyable
{
public:
    PatchFileFinderUtil() = delete;
    ~PatchFileFinderUtil() = delete;

public:
    static std::pair<Status, std::shared_ptr<indexlib::file_system::IDirectory>>
    GetOpLog2PatchRootDir(const framework::IndexOperationDescription& desc, const framework::IndexTaskContext& context);

    // Find all patches for AttributeMerger, including patches that are generated by OpLog2Patch operation, and patches
    // from merged segments.

    static Status FindPatchInfos(const indexlibv2::index::SrcDestPatchFileFinder* patchFileFinder,
                                 const std::shared_ptr<framework::TabletData>& tabletData,
                                 const std::shared_ptr<config::IIndexConfig>& indexConfig,
                                 const std::shared_ptr<indexlib::file_system::IDirectory>& opLog2PatchOpRootDir,
                                 indexlibv2::index::PatchInfos* allPatchInfos);

    static Status FindPatchInfos(const indexlibv2::index::SrcDestPatchFileFinder* patchFileFinder,
                                 const std::vector<std::shared_ptr<framework::Segment>>& srcSegments,
                                 const std::shared_ptr<config::IIndexConfig>& indexConfig,
                                 const std::shared_ptr<indexlib::file_system::IDirectory>& opLog2PatchOpRootDir,
                                 indexlibv2::index::PatchInfos* allPatchInfos);

private:
    static Status
    FindPatchesFromOpLog2Patch(const index::SrcDestPatchFileFinder* patchFinder,
                               const std::shared_ptr<indexlib::file_system::IDirectory>& opLog2PatchOpRootDir,
                               const std::shared_ptr<config::IIndexConfig>& indexConfig,
                               indexlibv2::index::PatchInfos* allPatchInfos);

    static Status LoadFromMetaFile(const std::shared_ptr<indexlib::file_system::IDirectory>& opLog2PatchRootDir,
                                   const std::shared_ptr<indexlib::file_system::IDirectory>& opLog2PatchWorkDir,
                                   indexlibv2::index::PatchInfos* allPatchInfos);

private:
    friend class AttributeIndexMergeOperationTest;
    AUTIL_LOG_DECLARE();
};

} // namespace indexlibv2::table
