node {
  name: "ha3_request"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_VARIANT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        unknown_rank: true
      }
    }
  }
}
node {
  name: "request_init"
  op: "Ha3RequestInitOp"
  input: "ha3_request"
}
node {
  name: "add_degrade"
  op: "AddDegradeInfoOp"
  input: "request_init"
}
node {
  name: "is_phase_one"
  op: "IsPhaseOneOp"
  input: "add_degrade"
}
node {
  name: "Switch"
  op: "Switch"
  input: "is_phase_one"
  input: "is_phase_one"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "switch_f"
  op: "Identity"
  input: "Switch"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "switch_t"
  op: "Identity"
  input: "Switch:1"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "seek_prepare"
  op: "Ha3SearcherPrepareOp"
  input: "add_degrade"
  input: "^switch_t"
}
node {
  name: "cache_prepare"
  op: "Ha3CachePrepareOp"
  input: "add_degrade"
  input: "^seek_prepare"
}
node {
  name: "ha3_request_to_kv_pair"
  op: "Ha3RequestToKvPairOp"
  input: "request_init"
}
node {
  name: "seek"
  op: "Ha3SeekOp"
  input: "add_degrade"
  input: "^cache_prepare"
  attr {
    key: "self_define_type"
    value {
      s: "Switch"
    }
  }
}
node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_UINT16
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_UINT16
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "Ha3SorterOp"
  op: "Ha3SorterOp"
  input: "add_degrade"
  input: "seek"
  input: "seek:1"
  input: "seek:2"
  input: "seek:3"
  input: "Const"
  attr {
    key: "attr_location"
    value {
      s: "SL_SEARCHER"
    }
  }
}
node {
  name: "release_before_fill_attributes"
  op: "Ha3ReleaseRedundantV2Op"
  input: "add_degrade"
  input: "Ha3SorterOp"
}
node {
  name: "Ha3FillAttributesOp"
  op: "Ha3FillAttributesOp"
  input: "add_degrade"
  input: "release_before_fill_attributes"
}
node {
  name: "phase1_result"
  op: "Ha3ResultConstructOp"
  input: "add_degrade"
  input: "Ha3FillAttributesOp"
  input: "Ha3SorterOp:1"
  input: "Ha3SorterOp:2"
  input: "seek:4"
}
node {
  name: "cache_switch"
  op: "Ha3SearcherCacheSwitchOp"
  input: "phase1_result"
  attr {
    key: "self_define_type"
    value {
      s: "Switch"
    }
  }
}
node {
  name: "put_cache"
  op: "Ha3SearcherPutCacheOp"
  input: "add_degrade"
  input: "cache_switch:1"
}
node {
  name: "refresh_attr"
  op: "Ha3CacheRefreshAttrOp"
  input: "add_degrade"
  input: "cache_switch:2"
}
node {
  name: "merge_cache_and_inc"
  op: "Ha3ResultMergeOp"
  input: "add_degrade"
  input: "refresh_attr"
  attr {
    key: "self_define_type"
    value {
      s: "Switch"
    }
  }
}
node {
  name: "cache_result_split"
  op: "Ha3ResultSplitOp"
  input: "add_degrade"
  input: "merge_cache_and_inc"
}
node {
  name: "ha3_cache_sorter"
  op: "Ha3SorterOp"
  input: "add_degrade"
  input: "cache_result_split"
  input: "cache_result_split:1"
  input: "cache_result_split:2"
  input: "cache_result_split:3"
  input: "cache_result_split:5"
  attr {
    key: "attr_location"
    value {
      s: "SL_SEARCHCACHEMERGER"
    }
  }
}
node {
  name: "reconstruct_after_cachesorter"
  op: "Ha3ResultReconstructOp"
  input: "cache_result_split:4"
  input: "ha3_cache_sorter"
  input: "ha3_cache_sorter:1"
  input: "ha3_cache_sorter:2"
}
node {
  name: "Merge"
  op: "Merge"
  input: "cache_switch"
  input: "put_cache"
  input: "reconstruct_after_cachesorter"
  input: "merge_cache_and_inc:1"
  attr {
    key: "N"
    value {
      i: 4
    }
  }
  attr {
    key: "T"
    value {
      type: DT_VARIANT
    }
  }
}
node {
  name: "release_redundant"
  op: "Ha3ReleaseRedundantOp"
  input: "Merge"
}
node {
  name: "fill_global_id"
  op: "Ha3FillGlobalIdInfoOp"
  input: "add_degrade"
  input: "release_redundant"
}
node {
  name: "phase2_result"
  op: "Ha3SummaryOp"
  input: "add_degrade"
  input: "^switch_f"
  attr {
    key: "force_allow_lack_of_summary"
    value {
      b: false
    }
  }
}
node {
  name: "ha3_result_merge"
  op: "Merge"
  input: "seek:5"
  input: "fill_global_id"
  input: "phase2_result"
  attr {
    key: "N"
    value {
      i: 3
    }
  }
  attr {
    key: "T"
    value {
      type: DT_VARIANT
    }
  }
}
node {
  name: "ha3_result"
  op: "Ha3EndIdentityOp"
  input: "ha3_result_merge"
  attr {
    key: "T"
    value {
      type: DT_VARIANT
    }
  }
}
node {
  name: "ha3_search_done"
  op: "NoOp"
  input: "^ha3_result"
}
versions {
  producer: 27
}
