cc_library(
    name='indexlib_codegen',
    srcs=[],
    hdrs=[
        'code_factory.h', 'codegen_checker.h', 'codegen_info.h',
        'codegen_object.h'
    ],
    copts=['-Werror'],
    include_prefix='indexlib/codegen',
    visibility=['//aios/storage/indexlib/indexlib:__subpackages__'],
    deps=[]
)
