# -*- mode: python -*-

Import('env')
env = env.Clone()

document = Glob('*.cpp')
rawdoc = env.aDirs('raw_document')
indexdoc = env.aDirs('index_document')
extdoc = env.aDirs('extend_document')
docparser = env.aDirs('document_parser')
document_rewriter = env.aDirs('document_rewriter')

document_cpps = [ document, rawdoc, indexdoc, extdoc, docparser, document_rewriter ]
env.aSharedLibrary(target = 'indexlib_document', source = document_cpps)

env.aDirs('test')
Return(['document_cpps'] )

