load('//aios/storage:defs.bzl', 'strict_cc_library')
package(default_visibility=['//aios/storage/indexlib:__subpackages__'])
strict_cc_library(
    name='MockPrimaryKeyIndexReader',
    srcs=[],
    deps=['//aios/storage/indexlib/index/primary_key:PrimaryKeyIndexReader']
)
