# -*- mode: python -*-
Import('env')
env = env.Clone()

util_test_sources = [
    '#indexlib/test/dotest.cpp',
    'common_disk_tiered_dictionary_reader_unittest.cpp',
    'tiered_dictionary_writer_unittest.cpp',
    'tiered_dictionary_reader_unittest.cpp',
    'hash_dictionary_writer_unittest.cpp',    
]

util_libs = [
    'indexlib_file_system_test_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'fslib-framework',
    'gmock',
    'gtest',
    'pthread'
]

env.aTest('ie_index_util_unittest', util_test_sources, LIBS=util_libs)

Return([])
