# -*- mode: python -*-

Import('env')
env = env.Clone()
source = Glob('*.cpp')

depend_libs = []

env.aLibrary(
    target='ha3_suez_turing_ops',
    LIBS = depend_libs,
    source = source)


env.aLibrary(
    target='ha3_suez_turing_opdef',
    source=['OpDefs.cpp'])

env.aDirs('agg')
env.aDirs('sql')
env.aDirs('test')
