# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

document_token_rewrite_processorsources = ['RewriteTokenDocumentProcessor.cpp', 'RewriteTokenDocumentProcessorFactory.cpp']
libdocument_token_rewrite_processor = env.aSharedLibrary(target  = 'document_token_rewrite_processor',
                                    source = document_token_rewrite_processorsources);


