# -*- mode: python -*-
Import('env')
env = env.Clone()

calculator_ut_test_sources = [
    '#indexlib/test/dotest.cpp',
    'partition_size_calculator_unittest.cpp',
    'segment_lock_size_calculator_unittest.cpp',
    'on_disk_segment_size_calculator_unittest.cpp',
]

env.aTest('indexlib_calculator_unittest', calculator_ut_test_sources,
          LIBS=['indexlib_indextest_common',
                'indexlib_file_system_test_common',
                'indexlib_attributetest',
                'indexlib_test',
                'indexlib_testlib',
                'indexlib_partition',
                'indexlib_merger',
                'indexlib_table',
                'indexlib_index',
                'indexlib_index_base',
                'indexlib_document',
                'indexlib_common',
                'indexlib_plugin',
                'indexlib_config',
                'indexlib_file_system',
                'indexlib_storage',
                'indexlib_util',
                'indexlib_misc',
                'fslib-framework',
                'gtest',
                'gmock',
                'pthread'
                ])

Return([])

