# -*- mode: python -*-

Import('env')
env = env.Clone()

partition_test_sources = [
    '#indexlib/test/dotest.cpp',
    'single_segment_writer_unittest.cpp',
    'sub_doc_segment_writer_unittest.cpp',
    'in_memory_segment_modifier_unittest.cpp',
    'in_memory_segment_creator_unittest.cpp',
    'in_memory_segment_container_unittest.cpp',
    'in_memory_segment_cleaner_unittest.cpp',
    'dump_segment_container_unittest.cpp',
    'dump_segment_queue_unittest.cpp',
]

segment_libs = [
    'indexlib_indextest_common',
    'indexlib_file_system_test_common',
    'indexlib_test',
    'indexlib_testlib',
    'indexlib_partition',
    'indexlib_merger',
    'indexlib_table',
    'indexlib_index',
    'indexlib_index_base',
    'indexlib_document',
    'indexlib_common',
    'indexlib_plugin',
    'indexlib_config',
    'indexlib_file_system',
    'indexlib_storage',
    'indexlib_util',
    'indexlib_misc',
    'gmock',
    'gtest',
]

env.aTest(target = 'indexlib_segment_unittest',
          source = partition_test_sources, LIBS = segment_libs)
