package(default_visibility=['//aios/network/rdma:__subpackages__'])
cc_library(
    name='arpc_metric_api',
    srcs=[],
    hdrs=[],
    deps=['//aios/network/arpc/arpc/metric:arpc_metric'],
    visibility=['//visibility:public']
)
