# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

testlib_rank_sources = Glob('*.cpp')

testlib_rank = env.aStaticLibrary(target = 'testlib_rank', source = testlib_rank_sources)

#env.aDirs('test')

Return(['testlib_rank_sources'])
