py_library(
    name='hippo_py_sdk',
    srcs=glob(['hippo_py_sdk/*.py', 'hippo_py_sdk/include/*.py']),
    data=['hippo_py_sdk/include/zookeeper_for_py2_7/zookeeper.so'],
    visibility=['//visibility:public'],
    imports=['.']
)
